
import { AuthTranslations } from '@/types/language/auth';

export const enAuthTranslations: AuthTranslations = {
  signIn: 'Sign In',
  signUp: 'Sign Up',
  signOut: 'Sign Out',
  signOutSuccess: 'Successfully signed out',
  signOutError: 'Error signing out',
  email: 'Email',
  password: 'Password',
  forgotPassword: 'Forgot Password',
  noAccount: 'Don\'t have an account?',
  hasAccount: 'Already have an account?',
  resetPassword: 'Reset Password',
  name: 'Name',
  loginSuccess: 'Successfully logged in',
  registerSuccess: 'Successfully registered',
  checkEmail: 'Please check your email',
  error: 'Error',
  processing: 'Processing...',
  loginButton: 'Login',
  registerButton: 'Register',
  loginTitle: 'Login to your account',
  registerTitle: 'Create a new account',
  loginDescription: 'Enter your email below to login to your account',
  registerDescription: 'Enter your information below to create your account',
  namePlaceholder: 'Enter your name',
  emailPlaceholder: 'Enter your email',
  passwordPlaceholder: 'Enter your password',
  needAccount: 'Need an account?',
  haveAccount: 'Already have an account?',
  welcomeTitle: 'Welcome back',
  welcomeSubtitle: 'Enter your credentials to continue',
  notAuthenticated: 'You need to be logged in'
};
