export const clientInfo = {
  title: "Client Information",
  name: "Client Name",
  namePlaceholder: "Enter client name",
  contactPerson: "Contact Person",
  contactPersonPlaceholder: "Enter contact person",
  address: "Address",
  addressPlaceholder: "Enter address",
  city: "City",
  cityPlaceholder: "Enter city",
  country: "Country",
  countryPlaceholder: "Enter country",
  vatNumber: "VAT Number",
  vatNumberPlaceholder: "Enter VAT number",
  email: "Email",
  emailPlaceholder: "Enter email",
  phone: "Phone",
  phonePlaceholder: "Enter phone number",
  selectExisting: "Select Existing Client",
  selectClient: "Select Client",
  searchClients: "Search clients...",
  nameRequired: "Client name is required",
};
