export const client = {
  title: "Client",
  firstName: "First Name",
  lastName: "Last Name",
  email: "Email",
  phone: "Phone",
  address: "Address",
  city: "City",
  country: "Country",
  postalCode: "Postal Code",
  companyName: "Company Name",
  vatNumber: "VAT Number",
  website: "Website",
  addNewClient: "Add New Client",
  updateClient: "Update Client",
  clientDetails: "Client Details",
  noClientsFound: "No clients found. Add your first client!",
  recentClients: "Recent Clients",
};
