
import { CommonTranslations } from '@/types/language/common';

export const common: CommonTranslations = {
  cancel: "Cancel",
  close: "Close",
  save: "Save",
  edit: "Edit",
  delete: "Delete",
  search: "Search",
  processing: "Processing",
  loading: "Loading",
  error: "Error",
  success: "Success",
  warning: "Warning",
  info: "Information",
  required: "Required",
  optional: "Optional",
  noResults: "No results found",
  actions: "Actions",
  selectOne: "Select one",
  new: "New",
  view: "View",
  chooseFile: "Choose file",
  upload: "Upload",
  remove: "Remove",
  add: "Add",
  created: "Created",
  updated: "Updated",
  save_changes: "Save changes",
  confirm: "Confirm",
  copy: "Copy",
  print: "Print",
  export: "Export",
  areYouSure: "Are you sure?",
  thisActionCannot: "This action cannot be undone",
  yes: "Yes",
  no: "No",
  confirmDelete: "Confirm Delete",
  confirmDeleteText: "Are you sure you want to delete this item?",
  viewImage: "View Image",
  selectDate: "Select Date",
  allProducts: "All Products",
  itemsSelected: "items selected",
  clear: "Clear",
  clearFilters: "Clear Filters",
  noDataAvailable: "No data available",
  today: "Today",
  day: "Day",
  week: "Week",
  month: "Month",
  year: "Year",
  or: "Or",
  and: "And",
  next: "Next",
  prev: "Previous",
  configuration: "Configuration",
  apply: "Apply",
  pageOf: "Page {current} of {total}",
  showingItems: "Showing {start}-{end} of {total} items",
  
  // Additional properties
  account: "Account",
  newOffer: "New Offer",
  newClient: "New Client",
  newProduct: "New Product",
  create: "Create",
  manageAccount: "Manage Account",
  back: "Back",
  confirmation: "Confirmation",
  all: "All",
  reset: "Reset",
  noName: "No Name",
  update: "Update",
  description: "Description",
  saving: "Saving...",
  home: "Home",
  templates: "Templates",
  navigation: "Navigation",
  preview: "Preview",
  retry: "Retry",
  welcome: "Welcome",
  unauthorized: "Unauthorized",
  expandAll: "Expand All",
  collapseAll: "Collapse All"
};
