
export const common = {
  language: 'Language',
  save: 'Save',
  cancel: 'Cancel',
  delete: 'Delete',
  edit: 'Edit',
  update: 'Update',
  create: 'Create',
  add: 'Add',
  remove: 'Remove',
  search: 'Search',
  loading: 'Loading...',
  noResults: 'No results',
  success: 'Success',
  error: 'Error',
  warning: 'Warning',
  info: 'Information',
  confirm: 'Confirm',
  back: 'Back',
  next: 'Next',
  submit: 'Submit',
  reset: 'Reset',
  select: 'Select',
  upload: 'Upload',
  download: 'Download',
  view: 'View',
  preview: 'Preview',
  print: 'Print',
  export: 'Export',
  import: 'Import',
  settings: 'Settings',
  help: 'Help',
  logout: 'Logout',
  login: 'Login',
  register: 'Register',
  required: 'Required',
  optional: 'Optional',
  all: 'All',
  none: 'None',
  noName: 'No name',
  noDescription: 'No description',
  saving: 'Saving...',
  areYouSure: 'Are you sure?',
  errorOccurred: 'An error occurred',
  copy: 'Copy',
  open: 'Open',
  close: 'Close',
  more: 'More',
  yes: 'Yes',
  no: 'No',
  actions: 'Actions',
  apply: 'Apply',
  confirm_delete: 'Are you sure you want to delete this?',
  confirm_reset: 'Are you sure you want to reset this?',
  continue: 'Continue',
  continue_anyway: 'Continue anyway',
  discard: 'Discard',
  discard_changes: 'Discard changes',
  dark_mode: 'Dark mode',
  light_mode: 'Light mode',
  system_theme: 'System theme',
  copy_to_clipboard: 'Copy to clipboard',
  copied_to_clipboard: 'Copied to clipboard',
  search_placeholder: 'Search...',
};
