
import { CompanyTranslations } from '@/types/language/company';

export const company: CompanyTranslations = {
  companyInfo: "Company Information",
  companyName: "Company Name",
  vatNumber: "VAT Number",
  address: "Address",
  city: "City",
  postalCode: "Postal Code",
  country: "Country",
  phone: "Phone",
  email: "Email",
  website: "Website",
  logoUrl: "Logo URL",
  description: "Description",
  contactPerson: "Contact Person",
  title: "Title",
  position: "Position",
  noCompany: "No Company Selected",
  selectFirst: "Please select a company first",
  selectCompany: "Select Company",
  createCompany: "Create Company",
  companyCreated: "Company created successfully",
  companyUpdated: "Company updated successfully",
  companyDeleted: "Company deleted successfully",
  companyDetails: "Company Details",
  addCompanyLogo: "Add Company Logo",
  logoUploadSuccess: "Logo uploaded successfully",
  logoUploadFail: "Failed to upload logo",
  selectPlaceholder: "Select Company",
  createNew: "Create New Company",
  createFirst: "Create First Company",
  useSelector: "Use the company selector above to continue",
  companySettings: "Company Settings",
  regNumber: "Reg. Number",
  companyInfo_bg: "Company Information (BG)",
  companyInfo_en: "Company Information (EN)",
  bankInfo: "Bank Information",
  bankName: "Bank Name",
  bankAccount: "Bank Account",
  bankCode: "Bank Code",
  swift: "SWIFT",
  iban: "IBAN",
  bankDetails: "Bank Details",
  members: "Team Members",
  inviteMembers: "Invite Members",
  owner: "Owner",
  admin: "Admin",
  member: "Member",
  viewer: "Viewer",
  companySelected: "Company Selected",
  companyChanged: "Company Changed",
  offerPreparation: "Preparing offer for the selected company...",
  updatingOffer: "Updating offer with the new company...",
  
  // Adding missing placeholders
  vatPlaceholder: "Enter VAT number",
  phonePlaceholder: "Enter phone number",
  emailPlaceholder: "Enter email address",
  websitePlaceholder: "Enter website URL",
  addressPlaceholder: "Enter address",
  cityPlaceholder: "Enter city",
  countryPlaceholder: "Enter country",
  namePlaceholder: "Enter company name",
  
  // Adding missing buttons and messages
  updateButton: "Update Company",
  create: "Create Company",
  createButton: "Create Company",
  manage: "Manage Companies",
  info: "View and edit your company information",
  
  // Adding missing error and success messages
  error: "Error",
  success: "Success",
  nameRequired: "Company name is required",
  createdSuccessfully: "Company created successfully"
};
