
import { Translations } from '@/types/language';

export const enTranslations: Translations = {
  offerTitle: 'Offer Forge',
  common: {
    edit: 'Edit',
    preview: 'Preview',
    previewOffer: 'Preview Offer',
    backToEdit: 'Back to Edit',
    save: 'Save',
    print: 'Print',
    add: 'Add',
    currency: 'Currency',
    loading: 'Loading...',
    processing: 'Processing...',
    error: 'An error occurred',
    success: 'Success',
    account: 'Account',
    settings: 'Settings',
    comingSoon: 'Coming Soon',
    featureInDevelopment: 'This feature is currently in development.'
  },
  auth: {
    signIn: 'Sign In',
    signUp: 'Sign Up',
    signOut: 'Sign Out',
    signOutSuccess: 'You have been signed out successfully',
    signOutError: 'Failed to sign out',
    email: 'Email',
    password: 'Password',
    forgotPassword: 'Forgot Password?',
    noAccount: 'Don\'t have an account?',
    hasAccount: 'Already have an account?',
    resetPassword: 'Reset Password',
    name: 'Name',
    loginSuccess: 'Signed in successfully',
    registerSuccess: 'Registration successful',
    checkEmail: 'Please check your email to confirm your account',
    error: 'Authentication error',
    processing: 'Processing...',
    loginButton: 'Sign In',
    registerButton: 'Sign Up',
    loginTitle: 'Sign in to your account',
    registerTitle: 'Create a new account',
    loginDescription: 'Enter your credentials to access your account',
    registerDescription: 'Fill out the form to create your account',
    namePlaceholder: 'Enter your name',
    emailPlaceholder: 'Enter your email',
    passwordPlaceholder: 'Enter your password',
    needAccount: 'Need an account?',
    haveAccount: 'Already have an account?',
    welcomeTitle: 'Welcome to Offer Forge',
    welcomeSubtitle: 'Create professional offers easily'
  },
  user: {
    profile: 'My Profile',
    editProfile: 'Edit Profile',
    name: 'Name',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    updateProfile: 'Update Profile'
  },
  company: {
    info: 'Company Information',
    name: 'Company Name',
    vatNumber: 'VAT Number',
    address: 'Address',
    city: 'City',
    country: 'Country',
    phone: 'Phone',
    email: 'Email',
    website: 'Website',
    logo: 'Logo',
    uploadLogo: 'Upload Logo',
    manage: 'Manage Company',
    selectFirst: 'Please select a company first',
    create: 'Create Company',
    createButton: 'Create',
    edit: 'Edit Company',
    update: 'Update Company',
    updateButton: 'Update',
    delete: 'Delete Company',
    deleteConfirm: 'Are you sure you want to delete this company?',
    error: 'Company Error',
    success: 'Company Success',
    nameRequired: 'Company name is required',
    createdSuccessfully: 'Company created successfully',
    createNew: 'Create New Company',
    createFirst: 'Please create your first company',
    selectPlaceholder: 'Select a company',
    namePlaceholder: 'Enter company name',
    vatPlaceholder: 'Enter VAT number',
    addressPlaceholder: 'Enter company address',
    cityPlaceholder: 'Enter city',
    countryPlaceholder: 'Enter country',
    phonePlaceholder: 'Enter phone number',
    emailPlaceholder: 'Enter email address',
    websitePlaceholder: 'Enter website URL'
  },
  client: {
    info: 'Client Information',
    name: 'Client Name',
    vatNumber: 'VAT Number',
    address: 'Address',
    email: 'Email',
    contactPerson: 'Contact Person',
    city: 'City',
    country: 'Country',
    phone: 'Phone'
  },
  clientInfo: {
    title: 'Client Information',
    name: 'Client Name',
    vatNumber: 'VAT Number',
    address: 'Address',
    contactPerson: 'Contact Person',
    city: 'City',
    country: 'Country',
    email: 'Email',
    phone: 'Phone'
  },
  companyInfo: {
    title: 'Company Information',
    name: 'Company Name',
    vatNumber: 'VAT Number',
    address: 'Address',
    city: 'City',
    country: 'Country',
    phone: 'Phone',
    email: 'Email',
    website: 'Website',
    logo: 'Logo',
    uploadLogo: 'Upload Logo'
  },
  offer: {
    details: 'Offer Details',
    number: 'Offer Number',
    date: 'Date',
    validUntil: 'Valid Until',
    notes: 'Notes',
    terms: 'Terms and Conditions',
    status: 'Status',
    statuses: {
      draft: 'Draft',
      sent: 'Sent',
      accepted: 'Accepted',
      rejected: 'Rejected'
    },
    offerLabel: 'OFFER',
    toLabel: 'To',
    attention: 'Attention:',
    item: 'Item',
    partNo: 'Part No.',
    qty: 'Qty',
    unitPrice: 'Unit Price',
    total: 'Total',
    vatIncluded: 'VAT included in the price',
    vatExcluded: 'VAT excluded from the price',
    thankYou: 'Thank you for your business!',
    language: 'Offer Language',
    languageOptions: {
      bulgarian: 'Bulgarian',
      english: 'English'
    }
  },
  offerDetails: {
    title: 'Offer Details',
    offerNumber: 'Offer Number',
    date: 'Date',
    validUntil: 'Valid Until',
    showPartNumber: 'Show Part Number',
    includeVat: 'Include VAT',
    vatRate: 'VAT Rate (%)',
    transportCost: 'Transport Cost',
    otherCosts: 'Other Costs',
    notes: 'Notes',
    notesPlaceholder: 'Add any additional notes or comments about the offer...',
    language: 'Language'
  },
  products: {
    title: 'Products',
    name: 'Product Name',
    description: 'Description',
    price: 'Price',
    quantity: 'Quantity',
    vat: 'VAT (%)',
    vatIncluded: 'VAT Included',
    total: 'Total',
    addProduct: 'Add Product',
    removeProduct: 'Remove Product',
    noProducts: 'No products added yet.',
    productName: 'Product Name',
    partNumber: 'Part Number',
    unitPrice: 'Unit Price'
  },
  totals: {
    subtotal: 'Subtotal',
    vat: 'VAT',
    transport: 'Transport',
    otherCosts: 'Other Costs',
    totalAmount: 'Total Amount'
  }
};
