
export const offerDetails = {
  title: "Offer Details",
  description: "Configure the details of your offer",
  offerNumber: "Offer Number",
  offerNumberInfo: "This number is automatically generated",
  date: "Date",
  validUntil: "Valid Until",
  validUntilPlaceholder: "Select expiration date",
  showPartNumber: "Show Product Code",
  includeVat: "Include VAT",
  vatIncluded: "Prices include VAT",
  vatExcluded: "Prices exclude VAT",
  vatRate: "VAT Rate (%)",
  transportCost: "Transport Cost",
  transportCostPlaceholder: "0.00",
  otherCosts: "Other Costs",
  otherCostsPlaceholder: "0.00",
  notes: "Notes",
  notesPlaceholder: "Additional information or terms",
  language: "Offer Language",
  currency: "Currency",
  // New translations
  specialDiscounts: "Special Discounts",
  addDiscount: "Add Discount",
  discountType: "Discount Type",
  discountAmount: "Discount Amount",
  discountDescription: "Discount Description",
  percentageDiscount: "Percentage Discount",
  fixedDiscount: "Fixed Amount",
  showDigitalSignature: "Show Digital Signature",
  customFooterText: "Additional Footer Text",
  customFooterTextPlaceholder: "Enter terms and conditions or additional text"
};
