
export const offer = {
  title: 'Offer',
  createOffer: 'Create Offer',
  offerDetails: 'Offer Details',
  offerPreview: 'Offer Preview',
  details: 'Details',
  backToOffer: "Back to Offer",
  number: "Number",
  date: "Date",
  validUntil: "Valid Until",
  notes: "Notes",
  terms: "Terms & Conditions",
  status: "Status",
  statuses: {
    draft: "Draft",
    sent: "Sent",
    accepted: "Accepted",
    rejected: "Rejected"
  },
  offerLabel: "Offer",
  toLabel: "To",
  attention: "Attention",
  item: "Item",
  partNo: "Part No.",
  qty: "Qty",
  unitPrice: "Unit Price",
  total: "Total",
  vatIncluded: "VAT Included",
  vatExcluded: "VAT Excluded",
  thankYou: "Thank you for your business",
  language: "Language",
  languageOptions: {
    bulgarian: "Bulgarian",
    english: "English"
  },
  templates: {
    title: 'Offer Templates',
    description: 'Template Description',
    useTemplate: 'Use Template',
    createFromCurrent: 'Create from Current Offer',
    templateName: 'Template Name',
    saveAsTemplate: 'Save as Template',
    templateSaved: 'Template Saved',
    noTemplates: 'No Templates',
    confirmDelete: 'Confirm Delete',
    deleteTemplate: 'Delete Template',
    templateDeleted: 'Template Deleted',
    defaultTemplates: 'Default Templates',
    userTemplates: 'User Templates',
    createNew: 'Create New Template',
    availableTemplates: 'Available Templates',
    noTemplatesFound: 'No templates found. Create one to get started!',
    noDescription: 'No description provided',
  },
};
