
export const offer = {
  title: "Offer",
  offerTitle: "Create Offer",
  details: "Offer Details",
  offerPreview: "Offer Preview",
  number: "Offer Number",
  date: "Offer Date",
  expirationDate: "Expiration Date",
  currency: "Currency",
  language: "Language",
  subject: "Subject",
  notes: "Notes",
  status: "Status",
  createOffer: "Create Offer",
  languageOptions: {
    bulgarian: "Bulgarian",
    english: "English"
  },
  statuses: {
    draft: "Draft",
    sent: "Sent",
    viewed: "Viewed",
    accepted: "Accepted",
    rejected: "Rejected",
  },
  vatIncluded: "VAT included",
  vatExcluded: "VAT not included",
  offerLabel: "OFFER",
  toLabel: "TO",
  attention: "Attention",
  item: "Item",
  partNo: "Part No.",
  qty: "Qty",
  unitPrice: "Unit Price",
  total: "Total",
  thankYou: "Thank you for your business!",
  validUntil: "Valid Until",
  templates: {
    title: "Templates",
    createNew: "Create New Template",
    availableTemplates: "Available Templates",
    noTemplatesFound: "No templates found. Create your first template!",
    noDescription: "No description provided",
    confirmDelete: "Are you sure you want to delete this template?",
    templateDeleted: "Template has been deleted successfully",
    defaultTemplates: "Default Templates",
    userTemplates: "User Templates",
    description: "Description",
    useTemplate: "Use Template",
    createFromCurrent: "Create from Current",
    templateName: "Template Name",
    saveAsTemplate: "Save as Template",
    templateSaved: "Template Saved",
    noTemplates: "No Templates",
    deleteTemplate: "Delete Template"
  },
};
