export const offer = {
  createOffer: 'Create Offer',
  saveOffer: 'Save Offer',
  confirmSave: 'Are you sure you want to save this offer?',
  saveDescription: 'This will overwrite any unsaved changes.',
  offerName: 'Offer Name',
  saveAsTemplate: 'Save as Template',
  saveAsDraft: 'Save as Draft',
  saveAsFinalized: 'Save as Finalized',
  savedSuccessfully: 'Offer saved successfully',
  saveFailed: 'Failed to save offer',
  clearConfirm: 'Are you sure you want to clear all fields?',
  currency: 'Currency',
  fromTemplate: 'From Template',
  header: 'Header',
  fromCompany: 'From Company',
  toCompany: 'To Company',
  date: 'Date',
  validUntil: 'Valid Until',
  reference: 'Reference',
  notes: 'Notes',
  item: 'Item',
  qty: 'Qty',
  unit: 'Unit',
  unitPrice: 'Unit Price',
  total: 'Total',
  saved: 'Saved',
  subtotal: 'Subtotal',
  vat: 'VAT',
  totalAmount: 'Total Amount',
  includeVat: 'Include VAT',
  previewTitle: 'Offer Preview',
  previewDescription: 'Preview your offer before sending it to the client.',
  partNo: 'Part No.',
  
  // Status related translations
  status: 'Status',
  draftStatus: 'Draft',
  draftStatusInfo: 'This offer is a draft and has not been finalized yet.',
  statuses: {
    draft: 'Draft',
    saved: 'Saved',
    sent: 'Sent',
    accepted: 'Accepted',
    rejected: 'Rejected',
  },
  
  // Time related translations
  createdAt: 'Created At',
  lastEdited: 'Last Edited',
  
  // Draft related translations
  draftLoaded: 'Draft Loaded',
  draftRestoredDescription: 'Your last draft has been restored.',
  draftSaved: 'Draft Saved',
  draftSavedDescription: 'Your current progress has been saved as a draft.',
  draftSaveError: 'Error Saving Draft',
  notSavedYet: 'Not Saved Yet',
  lastSaved: 'Last Saved',
  saving: 'Saving...',
  unsavedChanges: 'Unsaved Changes',
  saveManually: 'Save Manually',
  autoSaveEnabled: 'Auto Save Enabled',
  autoSaveDisabled: 'Auto Save Disabled',
  enableAutoSave: 'Enable Auto Save',
  disableAutoSave: 'Disable Auto Save',
  draftInProgress: 'Draft In Progress',
  returnToDraft: 'Return to Draft',
  noContentToSave: 'No Content to Save',
  addContentToSave: 'Add Content to Save',
  
  // Client info related translations
  toLabel: 'To',
  attention: 'Attention',
  
  // Language options
  languageOptions: {
    bulgarian: 'Bulgarian',
    english: 'English',
  },
  
  templates: {
    title: 'Templates',
    description: 'Manage your offer templates',
    empty: 'No templates found',
    create: 'Create Template',
    delete: 'Delete',
    confirmDelete: 'Are you sure you want to delete this template?',
    templateDeleted: 'Template deleted successfully',
    apply: 'Apply Template',
    createNew: 'Create New Template',
    name: 'Template Name',
    namePlaceholder: 'Enter template name',
    descriptionPlaceholder: 'Enter template description',
    save: 'Save Template',
    cancel: 'Cancel',
    saved: 'Template saved successfully',
    error: 'Error saving template',
    defaultTemplates: 'Default Templates',
    userTemplates: 'Your Templates',
    templateName: 'Template Name',
    noTemplates: 'No templates found',
    templateSaved: 'Template saved successfully',
    useTemplate: 'Use Template',
    createFromCurrent: 'Create from Current Offer',
    saveAsTemplate: 'Save as Template',
    noDescription: 'No description',
    availableTemplates: 'Available Templates',
    noTemplatesFound: 'No templates found',
    templatePreview: 'Template Preview',
    setAsDefault: 'Set as Default',
    resetToDefault: 'Reset to Default',
    defaultTemplate: 'Default Template',
    sampleTemplates: 'Sample Templates',
    textColor: 'Text Color',
    backgroundColor: 'Background Color',
    designTemplateType: 'Design Template',
    designTemplates: {
      classic: 'Classic',
      modernDark: 'Modern Dark',
      gradient: 'Gradient',
      businessPro: 'Business Pro'
    },
    // Additional template translations
    editTemplate: 'Edit Template',
    createTemplate: 'Create Template',
    settingsDescription: 'Configure your template settings',
    templateNamePlaceholder: 'Enter template name',
    templateDescriptionPlaceholder: 'Enter template description',
    designAndSettings: 'Design & Settings',
    design: 'Design',
    appearance: 'Appearance',
    layout: 'Layout',
    content: 'Content',
    header: 'Header',
    footer: 'Footer',
    templateDesign: 'Template Design',
    primaryColor: 'Primary Color',
    secondaryColor: 'Secondary Color',
    fontFamily: 'Font Family',
    fontSize: 'Font Size',
    roundedCorners: 'Rounded Corners',
    roundedCornersDesc: 'Use rounded corners for elements',
    showLogo: 'Show Logo',
    logoPosition: 'Logo Position',
    compactMode: 'Compact Mode',
    compactModeDesc: 'Reduce spacing between elements',
    borderless: 'Borderless',
    borderlessDesc: 'Remove borders from tables and elements',
    showCompanySlogan: 'Show Company Slogan',
    companyNameSize: 'Company Name Size',
    showOfferLabel: 'Show Offer Label',
    useGradient: 'Use Gradient',
    useShadow: 'Use Shadow',
    boldPrices: 'Bold Prices',
    showLineNumbers: 'Show Line Numbers',
    alternateRowColors: 'Alternate Row Colors',
    highlightTotals: 'Highlight Totals',
    showFooter: 'Show Footer',
    footerText: 'Footer Text',
    footerTextPlaceholder: 'Enter footer text',
    showBankDetails: 'Show Bank Details',
    showSignatureArea: 'Show Signature Area',
    signatureText: 'Signature Text',
    signatureTextPlaceholder: 'Enter signature text',
    includeSocialMedia: 'Include Social Media',
    useQRCode: 'Use QR Code',
    settingsSaved: 'Settings saved successfully',
    templateCreated: 'Template created successfully',
    failedToSaveSettings: 'Failed to save settings',
    failedToLoadTemplates: 'Failed to load templates',
    failedToCreateTemplate: 'Failed to create template',
    failedToDeleteTemplate: 'Failed to delete template',
    failedToUpdateTemplate: 'Failed to update template',
    failedToSetDefaultTemplate: 'Failed to set default template',
    defaultTemplateSet: 'Default template set successfully'
  }
};
