
export const savedClients = {
  title: "Saved Clients",
  createClient: "Create Client",
  createNew: "Create New Client",
  editClient: "Edit Client",
  updateClient: "Update Client",
  addNewClient: "Add New Client",
  deleteClient: "Delete Client",
  confirmDelete: "Are you sure you want to delete this client?",
  clientDeleted: "Client has been deleted successfully",
  clientUpdatedSuccess: "Client has been updated successfully",
  clientAddedSuccess: "Client has been added successfully",
  clientDeletedSuccess: "Client has been deleted successfully",
  clientLoaded: "Client has been loaded successfully",
  noClientsFound: "No clients found. Add your first client!",
  noClientsFoundSearch: "No clients found matching your search criteria",
  search: "Search clients",
  searchPlaceholder: "Search by name, email or company",
  searchByName: "Search by name",
  searchByVat: "Search by VAT",
  searchByEik: "Search by EIK",
  selectClient: "Select Client",
  cancel: "Cancel",
  importFromOffer: "Import from Offer",
  deleteConfirmation: "Are you sure you want to delete this client?",
  recentClients: "Recent Clients"
};
