export const savedOffers = {
  title: "Saved Offers",
  noOffers: "No saved offers yet.",
  loadOffer: "Load Offer",
  deleteOffer: "Delete Offer",
  confirmDelete: "Are you sure you want to delete this offer?",
  offerDeleted: "Offer deleted successfully.",
  offerLoaded: "Offer loaded successfully.",
  saveOffer: "Save Offer",
  saving: "Saving...",
  saved: "Offer saved!",
  saveError: "Failed to save offer.",
  deleteError: "Failed to delete offer.",
  loadError: "Failed to load offer.",
  saveBeforeAction: "Please save the offer before this action",
};
