
export const savedOffers = {
  title: "Saved Offers",
  saveOffer: "Save Offer",
  recentOffers: "Recent Offers",
  loadOffer: "Load Offer",
  deleteOffer: "Delete Offer",
  offerSaved: "Offer has been saved successfully",
  offerSavedWithDetails: "Offer has been saved successfully. Any new clients and products have also been added to your database.",
  offerDeleted: "Offer has been deleted successfully",
  offerLoaded: "Offer has been loaded successfully",
  noOffersFound: "No offers found. Create your first offer!",
  noOffersFoundSearch: "No offers found matching your search criteria",
  confirmDelete: "Are you sure you want to delete this offer?",
  date: "Date",
  client: "Client",
  amount: "Amount",
  actions: "Actions",
  search: "Search offers",
  searchPlaceholder: "Search by client name or offer number",
  clientName: "Client Name",
  offerNumber: "Offer Number",
  createNew: "Create New Offer",
  viewOffer: "View Offer"
};
