
import { SettingsTranslations } from '@/types/language/settings';

export const settings: SettingsTranslations = {
  title: "Settings",
  general: "General",
  appearance: "Appearance",
  layout: "Layout",
  content: "Content",
  template: "Template",
  details: "Details",
  templates: {
    classic: "Classic",
    modernDark: "Modern Dark",
    gradient: "Gradient",
    businessPro: "Business Pro",
    selectDesign: "Select Template Design"
  },
  offerTemplates: "Offer Templates",
  templatesDescription: "Manage your offer templates",
  preview: "Preview",
  templateName: "Template Name",
  templateNamePlaceholder: "Enter template name",
  templateDescription: "Description",
  templateDescriptionPlaceholder: "Enter template description",
  templateLanguage: "Template Language",
  selectLanguage: "Select language",
  primaryColor: "Primary Color",
  secondaryColor: "Secondary Color",
  textColor: "Text Color",
  fontFamily: "Font Family",
  selectFont: "Select font",
  fontSize: "Font Size",
  selectFontSize: "Select font size",
  roundedCorners: "Rounded Corners",
  roundedCornersDescription: "Use rounded corners for elements",
  showLogo: "Show Logo",
  showLogoDescription: "Display company logo",
  logoPosition: "Logo Position",
  selectLogoPosition: "Select logo position",
  compactMode: "Compact Mode",
  compactModeDescription: "Reduce spacing and font sizes",
  fullWidth: "Full Width",
  fullWidthDescription: "Use full width for the offer",
  borderless: "Borderless",
  borderlessDescription: "Remove borders from elements",
  useShadows: "Use Shadows",
  useShadowsDescription: "Add shadows to elements",
  boldPrices: "Bold Prices",
  boldPricesDescription: "Display prices in bold",
  alternateRowColors: "Alternate Row Colors",
  alternateRowColorsDescription: "Use alternating colors for table rows",
  showLineNumbers: "Show Line Numbers",
  showLineNumbersDescription: "Display line numbers in the products table",
  showFooter: "Show Footer",
  showFooterDescription: "Display footer text",
  footerText: "Footer Text",
  showBankDetails: "Show Bank Details",
  showBankDetailsDescription: "Display bank information in the footer",
  showSignatureArea: "Show Signature Area",
  showSignatureAreaDescription: "Include an area for signature",
  signatureText: "Signature Text",
  useQRCode: "Use QR Code",
  useQRCodeDescription: "Include QR code for digital reference",
  showCompanySlogan: "Show Company Slogan",
  showCompanySloganDescription: "Display company slogan in the header",
  companyNameSize: "Company Name Size",
  selectSize: "Select size",
  showOfferLabel: "Show Offer Label",
  showOfferLabelDescription: "Display 'OFFER' label in the header",
  updateTemplate: "Update Template",
  saveTemplate: "Save Template",
  templateSaved: "Template saved successfully",
  small: "Small",
  medium: "Medium",
  large: "Large",
  left: "Left",
  center: "Center",
  right: "Right"
};
