
import { SettingsTranslations } from '@/types/language/settings';

export const settings: SettingsTranslations = {
  title: "Settings",
  subtitle: "Configure your application settings",
  general: "General",
  appearance: "Appearance",
  layout: "Layout",
  content: "Content",
  template: "Template",
  details: "Details",
  templates: {
    classic: "Classic",
    modernDark: "Modern Dark",
    gradient: "Gradient",
    businessPro: "Business Pro",
    selectDesign: "Select Template Design"
  },
  offerTemplates: "Offer Templates",
  templatesDescription: "Manage your offer templates",
  preview: "Preview",
  templateName: "Template Name",
  templateNamePlaceholder: "Enter template name",
  templateDescription: "Description",
  templateDescriptionPlaceholder: "Enter template description",
  templateLanguage: "Template Language",
  selectLanguage: "Select language",
  primaryColor: "Primary Color",
  secondaryColor: "Secondary Color",
  textColor: "Text Color",
  fontFamily: "Font Family",
  selectFont: "Select font",
  fontSize: "Font Size",
  selectFontSize: "Select font size",
  roundedCorners: "Rounded Corners",
  roundedCornersDescription: "Use rounded corners for elements",
  showLogo: "Show Logo",
  showLogoDescription: "Display company logo",
  logoPosition: "Logo Position",
  selectLogoPosition: "Select logo position",
  compactMode: "Compact Mode",
  compactModeDescription: "Reduce spacing and font sizes",
  fullWidth: "Full Width",
  fullWidthDescription: "Use full width for the offer",
  borderless: "Borderless",
  borderlessDescription: "Remove borders from elements",
  useShadows: "Use Shadows",
  useShadowsDescription: "Add shadows to elements",
  boldPrices: "Bold Prices",
  boldPricesDescription: "Display prices in bold",
  alternateRowColors: "Alternate Row Colors",
  alternateRowColorsDescription: "Use alternating colors for table rows",
  showLineNumbers: "Show Line Numbers",
  showLineNumbersDescription: "Display line numbers in the products table",
  showFooter: "Show Footer",
  showFooterDescription: "Display footer text",
  footerText: "Footer Text",
  showBankDetails: "Show Bank Details",
  showBankDetailsDescription: "Display bank information in the footer",
  showSignatureArea: "Show Signature Area",
  showSignatureAreaDescription: "Include an area for signature",
  signatureText: "Signature Text",
  useQRCode: "Use QR Code",
  useQRCodeDescription: "Include QR code for digital reference",
  showCompanySlogan: "Show Company Slogan",
  showCompanySloganDescription: "Display company slogan in the header",
  companyNameSize: "Company Name Size",
  selectSize: "Select size",
  showOfferLabel: "Show Offer Label",
  showOfferLabelDescription: "Display 'OFFER' label in the header",
  updateTemplate: "Update Template",
  saveTemplate: "Save Template",
  templateSaved: "Template saved successfully",
  small: "Small",
  medium: "Medium",
  large: "Large",
  left: "Left",
  center: "Center",
  right: "Right",
  
  // Additional properties
  bankDetails: "Bank Details",
  bankName: "Bank Name",
  bankNamePlaceholder: "Enter bank name",
  iban: "IBAN",
  ibanPlaceholder: "Enter IBAN",
  swift: "SWIFT/BIC",
  swiftPlaceholder: "Enter SWIFT/BIC code",
  additionalInfo: "Additional Info",
  additionalInfoPlaceholder: "Additional bank information",
  errorLoadingSettings: "Error loading settings",
  validationError: "Validation Error",
  unitNameRequired: "Unit name is required",
  unitAdded: "Unit Added",
  unitAddedSuccess: "Custom unit added successfully",
  errorSavingSettings: "Error Saving Settings",
  unitAddError: "Could not add custom unit",
  unitDeleted: "Unit Deleted",
  unitDeletedSuccess: "Custom unit deleted successfully",
  unitDeleteError: "Could not delete custom unit",
  customUnits: "Custom Units",
  customUnitsDescription: "Manage custom units of measurement",
  unitNameBg: "Bulgarian Name",
  unitNamePlaceholderBg: "e.g. брой",
  unitNameEn: "English Name",
  unitNamePlaceholderEn: "e.g. piece",
  addUnit: "Add Unit",
  existingUnits: "Existing Units",
  noCustomUnits: "No custom units defined",
  offerSettings: "Offer Settings",
  usePrefix: "Use Prefix",
  usePrefixDescription: "Add prefix to offer numbers",
  prefix: "Prefix",
  prefixDescription: "Prefix text for offer numbers",
  suffixYear: "Add Year Suffix",
  suffixYearDescription: "Add current year to offer numbers",
  defaultVatRate: "Default VAT Rate",
  defaultVatRateDescription: "Default VAT percentage for new offers",
  newTemplate: "New Template",
  createTemplate: "Create Template",
  createNewTemplate: "Create New Template",
  editTemplate: "Edit Template",
  viewTemplate: "View Template",
  defaultTemplatesDescription: "System default templates",
  default: "Default",
  useTemplate: "Use Template",
  setAsDefault: "Set as Default",
  noTemplates: "No Templates",
  confirmDeleteTemplate: "Are you sure you want to delete this template?",
  templateDeleted: "Template Deleted",
  deleteTemplateFailed: "Failed to delete template",
  templateUpdated: "Template Updated",
  templateCreated: "Template Created",
  saveTemplateFailed: "Failed to save template",
  defaultTemplateSet: "Default template set",
  setDefaultFailed: "Failed to set default template",
  userTemplates: "User Templates",
  sampleTemplates: "Sample Templates",
  showUserTemplatesOnly: "Show User Templates Only",
  settingsSaved: "Settings saved successfully",
  noTemplateSelected: "No template selected",
  
  // New properties for template settings
  basicInformation: "Basic Information",
  description: "Description",
  header: "Header",
  footer: "Footer",
  appearanceSettings: "Appearance Settings",
  pickColor: "Pick a color",
  headerSettings: "Header Settings",
  showCompanyLogo: "Show Company Logo",
  showCompanyName: "Show Company Name",
  useGradient: "Use Gradient Background",
  contentSettings: "Content Settings",
  showProductDescription: "Show Product Description",
  showPartNumbers: "Show Part Numbers",
  footerTextPlaceholder: "Enter footer text",
  footerTextDescription: "Text to display in the footer",
  footerSettings: "Footer Settings",
  signatureTextPlaceholder: "Enter signature text",
  includeSocialMedia: "Include Social Media Links",
  
  // Navigation and editing properties
  edit: "Edit",
  resetToDefault: "Reset to Default",
  
  // Color label properties
  primaryColorLabel: "Primary Color",
  secondaryColorLabel: "Secondary Color",
  textColorLabel: "Text Color",
  borderColorLabel: "Border Color",
  backgroundColor: "Background Color",
  backgroundColorLabel: "Background Color",
  tableHeaderColorLabel: "Table Header Color",
  tableRowAlternateColorLabel: "Alternate Row Color",
  buttonColorLabel: "Button Color",
  fontFamilyLabel: "Font Family",
  fontSizeLabel: "Font Size",
  headerBackgroundColorLabel: "Header Background Color",
  headerTextColorLabel: "Header Text Color",
  tableBorderStyleLabel: "Table Border Style",
  tableBorderWidthLabel: "Border Width",
  tableBorderColorLabel: "Table Border Color",
  footerBackgroundColorLabel: "Footer Background Color",
  footerTextColorLabel: "Footer Text Color",
  fullWidthLabel: "Full Width",
  borderRadiusLabel: "Border Radius",
  paddingLabel: "Padding",
};
