
export const offerProducts = {
  addProducts: "Add Products",
  addNewProduct: "Add New Product",
  noProductsAdded: "No products added yet.",
  productName: "Product Name",
  quantity: "Quantity",
  unitPrice: "Unit Price",
  totalPrice: "Total Price",
  removeProduct: "Remove Product",
  editProduct: "Edit Product",
  productDetails: "Product Details",
  productNamePlaceholder: "Enter product name",
  quantityPlaceholder: "Enter quantity",
  unitPricePlaceholder: "Enter unit price",
  saveProduct: "Save Product",
  showPartNumber: "Show Part Number",
  partNumber: "Part Number",
  includeVat: "Include VAT",
  vatRate: "VAT Rate",
  transportCost: "Transport Cost",
  otherCosts: "Other Costs",
  total: "Total",
  subtotal: "Subtotal",
  vat: "VAT",
  totalAmount: "Total Amount",
  item: "Item",
  qty: "Qty",
  productDescription: "Product Description",
  descriptionPlaceholder: "Enter product description",
  unit: "Unit",
  selectUnit: "Select Unit",
  noUnit: "No Unit",
  productImage: "Product Image",
  uploadImage: "Upload Image",
  imageUploaded: "Image uploaded successfully",
  imageDeleted: "Image deleted successfully",
  noImage: "No image"
};
