
export const offerDraft = {
  draftInProgress: "Draft in Progress",
  draftSaved: "Draft Saved",
  draftSavedDescription: "Your offer has been saved as a draft.",
  draftSaveError: "Error saving draft",
  draftSavedToLocalStorage: "Draft saved to local storage as a backup.",
  autoSaveDisabled: "Auto-save Disabled",
  autoSaveEnabled: "Auto-save Enabled",
  noContentToSave: "No Content to Save",
  addContentToSave: "Add some content to save as a draft.",
  returnToDraft: "Continue working from your saved draft",
  draftLoaded: "Draft Loaded",
  draftRestoredDescription: "Successfully restored your draft",
  lastSaved: "Last saved {time}",
  notSavedYet: "Not saved yet",
  saving: "Saving...",
  saved: "Saved",
  unsavedChanges: "Unsaved Changes",
  saveManually: "Save Manually",
  disableAutoSave: "Disable Auto Save",
  enableAutoSave: "Enable Auto Save",
  draftStatus: "Draft Offer",
  continueWorking: "Continue working on your draft offer",
  openDraft: "Open Draft"
};
