
export const offerBase = {
  createOffer: "Create Offer",
  offerDetails: "Offer Details",
  companyInfo: "Company Info",
  clientInfo: "Client Info",
  productsAndServices: "Products & Services",
  previewAndSave: "Preview & Save",
  previewAndFinish: "Preview & Finish",
  offerName: "Offer Name",
  offerNumber: "Offer Number",
  offerDate: "Offer Date",
  date: "Date",
  validUntil: "Valid Until",
  currency: "Currency",
  notes: "Notes",
  offerLanguage: "Offer Language",
  bulgarian: "Bulgarian",
  english: "English",
  offerNamePlaceholder: "Enter offer name",
  header: "Header",
  fromCompany: "From Company",
  toCompany: "To Company",
  reference: "Reference",
  toLabel: "To",
  attention: "Attention",
  bgn: "BGN",
  eur: "EUR",
  usd: "USD",
  cancel: "Cancel",
  
  // Additional properties to match interface
  previewTitle: "Preview",
  previewDescription: "Preview your offer before saving",
  saveOffer: "Save Offer",
  confirmSave: "Confirm Save",
  saveDescription: "Save your offer to access it later",
  saveAsTemplate: "Save as Template",
  saveAsDraft: "Save as Draft",
  saveAsFinalized: "Save as Finalized",
  savedSuccessfully: "Saved Successfully",
  saveFailed: "Save Failed",
  generatePdf: "Generate PDF",
  clearConfirm: "Clear Confirmation",
  fromTemplate: "From Template",
  item: "Item",
  qty: "Qty",
  total: "Total",
  subtotal: "Subtotal",
  vat: "VAT",
  totalAmount: "Total Amount",
  
  // Language options
  languageOptions: {
    bulgarian: "Bulgarian",
    english: "English",
  }
};
