
export const offerTemplates = {
  templates: {
    title: "Offer Templates",
    description: "Manage your personalized offer templates",
    primaryColor: "Primary Color",
    tableHeaderColor: "Table Header Color",
    orientation: "Orientation",
    portrait: "Portrait",
    landscape: "Landscape",
    applyChanges: "Apply Changes",
    templateSaved: "Template Saved",
    defaultTemplate: "Default Template",
    customizeAppearance: "Customize Appearance",
    chooseColor: "Choose Color",
    currentTemplate: "Current Template",
    chooseTemplate: "Choose Template",
    noTemplates: "No templates found",
    overwriteTemplate: "Overwrite Template",
    templateDeleted: "Template Deleted",
    chooseDefaultTemplate: "Choose Default Template",
    templateNameRequired: "Template name is required",
    useTemplate: "Use",
    createFromCurrent: "Create from current offer",
    empty: "No templates",
    create: "Create Template",
    delete: "Delete Template",
    confirmDelete: "Are you sure you want to delete this template?",
    designTemplates: {
      classic: "Classic",
      modernDark: "Modern Dark"
    }
  },
  saveAsTemplate: "Save as Template",
  createTemplate: "Create Template",
  deleteTemplate: "Delete Template",
  deleteTemplateConfirm: "Are you sure you want to delete this template?",
  applyTemplate: "Apply Template",
  noTemplatesFound: "No templates found",
  templateApplied: "Template Applied",
  templateName: "Template Name",
  templateDescription: "Template Description",
  templateNamePlaceholder: "Enter template name",
  templateDescriptionPlaceholder: "Enter template description",
  createAndApply: "Create & Apply",
};
