
export const offerTemplates = {
  createTemplate: "Create Template",
  saveAsTemplate: "Save as Template",
  applyTemplate: "Apply Template",
  noTemplatesFound: "No templates found",
  templateApplied: "Template applied successfully",
  templateName: "Template Name",
  templateDescription: "Template Description",
  templateNamePlaceholder: "Enter template name",
  templateDescriptionPlaceholder: "Enter template description",
  applyThisTemplate: "Apply This Template",
  templateCreated: "Template created successfully",
  templateUpdated: "Template updated successfully",
  templateDeleted: "Template deleted successfully",
  templateSaved: "Template Saved",
  templateSaveError: "Error saving template",
  defaultTemplate: "Default",
  setDefaultTemplate: "Set as default template",
  resetToDefault: "Reset to default",
  customizeTemplate: "Customize template",
  sectionSettings: "Section settings",
  headerSettings: "Header settings",
  footerSettings: "Footer settings",
  companyLogo: "Company logo",
  companySlogan: "Company slogan",
  clientLogo: "Client logo",
  clientDetails: "Client details",
  showClientLogo: "Show client logo",
  showClientDetails: "Show client details",
  productTableSettings: "Product table settings",
  showProductImage: "Show product image",
  showProductDescription: "Show product description",
  totalSettings: "Total settings",
  showTotal: "Show total",
  termsAndConditions: "Terms and conditions",
  thankYouMessage: "Thank you message",
  saveTemplate: "Save template",
  createOfferTemplate: "Create offer template",
  manageOfferTemplates: "Manage offer templates",
  offerTemplateName: "Offer template name",
  offerTemplateDescription: "Offer template description",
  fromTemplate: "From Template",
  
  // Templates related translations
  templates: {
    title: "Templates",
    description: "Manage your templates",
    empty: "No templates found",
    create: "Create Template",
    delete: "Delete Template",
    confirmDelete: "Are you sure you want to delete this template?",
    templateDeleted: "Template deleted",
    apply: "Apply Template",
    createNew: "Create New Template",
    name: "Template Name",
    namePlaceholder: "Enter template name",
    descriptionPlaceholder: "Enter template description",
    save: "Save Template",
    cancel: "Cancel",
    saved: "Template Saved",
    error: "Error saving template",
    defaultTemplates: "Default Templates",
    userTemplates: "Your Templates",
    templateName: "Template Name",
    noTemplates: "No templates found",
    templateSaved: "Template saved",
    useTemplate: "Use Template",
    createFromCurrent: "Create from current",
    saveAsTemplate: "Save as Template",
    noDescription: "No description",
    availableTemplates: "Available Templates",
    noTemplatesFound: "No templates found",
    templatePreview: "Template Preview",
    setAsDefault: "Set as Default",
    resetToDefault: "Reset to Default",
    defaultTemplate: "Default Template",
    sampleTemplates: "Sample Templates",
    textColor: "Text Color",
    backgroundColor: "Background Color",
    designTemplateType: "Design Template",
    designTemplates: {
      classic: "Classic",
      modernDark: "Modern Dark",
      gradient: "Gradient",
      businessPro: "Business Pro",
    },
    currentTemplate: "Current Template",
    chooseTemplate: "Choose Template",
    overwriteTemplate: "Overwrite Template",
    chooseDefaultTemplate: "Choose Default Template",
    templateNameRequired: "Template name is required"
  }
};
