
export const offerTemplates = {
  createTemplate: "Create Template",
  saveAsTemplate: "Save as Template",
  applyTemplate: "Apply Template",
  noTemplatesFound: "No templates found",
  templateApplied: "Template applied successfully",
  templateName: "Template Name",
  templateDescription: "Template Description",
  templateNamePlaceholder: "Enter template name",
  templateDescriptionPlaceholder: "Enter template description",
  applyThisTemplate: "Apply This Template",
  templateCreated: "Template created successfully",
  templateUpdated: "Template updated successfully",
  templateDeleted: "Template deleted successfully",
  templateSaved: "Template Saved",
  templateSaveError: "Error saving template",
  defaultTemplate: "Default",
  setDefaultTemplate: "Set as default template",
  resetToDefault: "Reset to default",
  customizeTemplate: "Customize template",
  sectionSettings: "Section settings",
  headerSettings: "Header settings",
  footerSettings: "Footer settings",
  companyLogo: "Company logo",
  companySlogan: "Company slogan",
  clientLogo: "Client logo",
  clientDetails: "Client details",
  showClientLogo: "Show client logo",
  showClientDetails: "Show client details",
  productTableSettings: "Product table settings",
  showProductImage: "Show product image",
  showProductDescription: "Show product description",
  totalSettings: "Total settings",
  showTotal: "Show total",
  termsAndConditions: "Terms and conditions",
  thankYouMessage: "Thank you message",
  saveTemplate: "Save template",
  createOfferTemplate: "Create offer template",
  manageOfferTemplates: "Manage offer templates",
  offerTemplateName: "Offer template name",
  offerTemplateDescription: "Offer template description",
  fromTemplate: "From Template",
  deleteTemplate: "Delete Template",
  deleteTemplateConfirm: "Are you sure you want to delete this template?",
  
  templates: {
    title: "Templates",
    description: "Manage offer appearance",
    primaryColor: "Primary Color",
    tableHeaderColor: "Table Header Color",
    orientation: "Orientation",
    portrait: "Portrait",
    landscape: "Landscape",
    applyChanges: "Apply Changes",
    templateSaved: "Changes saved",
    defaultTemplate: "Default Template",
    customizeAppearance: "Customize Appearance",
    chooseColor: "Choose color",
    
    // Add missing properties
    currentTemplate: "Current Template",
    chooseTemplate: "Choose Template",
    noTemplates: "No templates found",
    overwriteTemplate: "Overwrite Template",
    templateDeleted: "Template deleted",
    chooseDefaultTemplate: "Choose Default Template",
    templateNameRequired: "Template name is required",
    useTemplate: "Use Template",
    createFromCurrent: "Create from current"
  }
};
