
import { 
  ClientTranslations, 
  ClientInfoTranslations, 
  CompanyInfoTranslations,
  SavedClientsTranslations
} from '@/types/language/client';

export const bgClientTranslations: ClientTranslations = {
  title: 'Клиенти',
  name: 'Име',
  vatNumber: 'ЕИК/ДДС номер',
  contactPerson: 'Лице за контакт',
  email: 'Имейл',
  phone: 'Телефон',
  address: 'Адрес',
  city: 'Град',
  country: 'Държава',
  selectExisting: 'Избери съществуващ клиент',
  selectClient: 'Избери клиент',
  searchClients: 'Търси клиенти',
  noClientsFound: 'Няма намерени клиенти',
  noClientsFoundSearch: 'Няма намерени клиенти, отговарящи на търсенето',
  
  // Adding missing properties
  addClient: 'Добави клиент',
  editClient: 'Редактирай клиент',
  deleteClient: 'Изтрий клиент',
  deleteConfirmation: 'Сигурни ли сте, че искате да изтриете този клиент?',
  searchPlaceholder: 'Търси клиенти',
  actions: 'Действия',
  search: 'Търсене',
  createNew: 'Създай нов клиент',
  clientCreated: 'Клиентът е създаден успешно',
  clientUpdated: 'Клиентът е актуализиран успешно',
  clientDeleted: 'Клиентът е изтрит успешно',
  cancel: 'Отказ',
  save: 'Запази',
  clientSaved: 'Клиентът е запазен успешно',
  searchByName: 'Търсене по име',
  searchByVat: 'Търсене по ЕИК/ДДС номер'
};

export const bgClientInfoTranslations: ClientInfoTranslations = {
  title: 'Информация за клиента',
  name: 'Име на клиента',
  namePlaceholder: 'Въведете име на клиента',
  contactPerson: 'Лице за контакт',
  contactPersonPlaceholder: 'Въведете име на лице за контакт',
  address: 'Адрес',
  addressPlaceholder: 'Въведете адрес на клиента',
  city: 'Град',
  cityPlaceholder: 'Въведете град',
  country: 'Държава',
  countryPlaceholder: 'Въведете държава',
  vatNumber: 'ЕИК/ДДС номер',
  vatNumberPlaceholder: 'Въведете ЕИК/ДДС номер',
  email: 'Имейл',
  emailPlaceholder: 'Въведете имейл адрес',
  phone: 'Телефон',
  phonePlaceholder: 'Въведете телефонен номер',
  selectExisting: 'Избери съществуващ клиент',
  selectClient: 'Избери клиент',
  searchClients: 'Търсене на клиенти...'
};

export const bgCompanyInfoTranslations: CompanyInfoTranslations = {
  title: 'Информация за фирмата',
  name: 'Име на фирмата',
  address: 'Адрес',
  city: 'Град',
  country: 'Държава',
  vatNumber: 'ЕИК/ДДС номер',
  phone: 'Телефон',
  email: 'Имейл',
  website: 'Уебсайт',
  logo: 'Лого',
  uploadLogo: 'Качи лого',
  removeLogo: 'Премахни лого',
  selectLogo: 'Избери лого',
  changeLogo: 'Промени лого',
  companyUpdated: 'Информацията за фирмата е актуализирана успешно'
};

export const bgSavedClientsTranslations: SavedClientsTranslations = {
  title: 'Запазени клиенти',
  name: 'Име',
  vatNumber: 'ЕИК/ДДС номер',
  contactPerson: 'Лице за контакт',
  email: 'Имейл',
  phone: 'Телефон',
  address: 'Адрес',
  city: 'Град',
  country: 'Държава',
  actions: 'Действия',
  editClient: 'Редактирай',
  deleteClient: 'Изтрий',
  deleteConfirmation: 'Сигурни ли сте, че искате да изтриете този клиент?',
  search: 'Търсене',
  searchPlaceholder: 'Търсене по име на клиент, ЕИК/ДДС номер или лице за контакт',
  noClientsFound: 'Няма намерени запазени клиенти',
  noClientsFoundSearch: 'Няма намерени клиенти, отговарящи на търсенето',
  createClient: 'Създай клиент',
  clientCreated: 'Клиентът е създаден успешно',
  clientUpdated: 'Клиентът е актуализиран успешно',
  clientDeleted: 'Клиентът е изтрит успешно',
  
  // Adding missing properties
  loadClient: 'Зареди',
  saveClient: 'Запази клиент',
  clientSaved: 'Клиентът е запазен успешно',
  confirmDelete: 'Сигурни ли сте, че искате да изтриете този клиент?',
  date: 'Дата',
  client: 'Клиент',
  contact: 'Контакт',
  clientName: 'Име на клиент',
  contactName: 'Име на контакт',
  createNew: 'Създай нов клиент',
  clientLoaded: 'Клиентът е зареден успешно',
  viewClient: 'Преглед на клиент',
  selectClient: 'Избери',
  addNewClient: 'Добави нов клиент',
  updateClient: 'Актуализирай клиент',
  cancel: 'Отказ',
  importFromOffer: 'Импортирай от оферта',
  searchByName: 'Търсене по име',
  searchByVat: 'Търсене по ЕИК/ДДС номер',
  clientUpdatedSuccess: 'Клиентът е актуализиран успешно',
  clientAddedSuccess: 'Клиентът е добавен успешно',
  clientDeletedSuccess: 'Клиентът е изтрит успешно'
};
