export const clientInfo = {
  title: "Информация за клиента",
  name: "Име на клиент",
  namePlaceholder: "Въведете име на клиент",
  contactPerson: "Контактно лице",
  contactPersonPlaceholder: "Въведете име на контактно лице",
  address: "Адрес",
  addressPlaceholder: "Въведете адрес",
  city: "Град",
  cityPlaceholder: "Въведете град",
  country: "Държава",
  countryPlaceholder: "Въведете държава",
  vatNumber: "ДДС номер",
  vatNumberPlaceholder: "Въведете ДДС номер",
  email: "Имейл",
  emailPlaceholder: "Въведете имейл",
  phone: "Телефон",
  phonePlaceholder: "Въведете телефон",
  selectExisting: "Избор на съществуващ клиент",
  selectClient: "Изберете клиент",
  searchClients: "Търсене на клиенти",
  nameRequired: "Името на клиента е задължително",
};
