
export const clientInfo = {
  title: "Информация за клиента",
  description: "Въведете информация за клиента",
  clientDetails: "Детайли за клиента",
  name: "Име",
  contactPerson: "Лице за контакт",
  contactPersonName: "Име на лицето за контакт",
  contactPersonPosition: "Позиция",
  contactPersonEmail: "Имейл",
  contactPersonPhone: "Телефон",
  address: "Адрес",
  city: "Град",
  country: "Държава",
  vatNumber: "Номер по ДДС",
  eikNumber: "ЕИК",
  email: "Имейл",
  phone: "Телефон",
  website: "Уебсайт",
  namePlaceholder: "напр. Фирма ООД",
  contactPersonPlaceholder: "напр. Иван Иванов",
  addressPlaceholder: "напр. бул. България 58",
  cityPlaceholder: "напр. София",
  countryPlaceholder: "напр. България",
  vatNumberPlaceholder: "напр. BG123456789",
  eikNumberPlaceholder: "напр. 123456789",
  emailPlaceholder: "напр. office@example.com",
  phonePlaceholder: "напр. +359 888 123 456",
  websitePlaceholder: "напр. example.com",
  selectClient: "Избери клиент",
  selectExisting: "Избери съществуващ клиент",
  searchClients: "Търси клиенти",
  nameRequired: "Името е задължително",
  addContact: "Добави контакт",
  removeContact: "Премахни контакт",
  billingAddress: "Адрес за фактуриране",
  shippingAddress: "Адрес за доставка",
  sameAsBilling: "Същият като за фактуриране"
};
