
export const common = {
  language: 'Език',
  save: 'Запази',
  cancel: 'Отказ',
  delete: 'Изтрий',
  edit: 'Редактирай',
  update: 'Обнови',
  create: 'Създай',
  add: 'Добави',
  remove: 'Премахни',
  search: 'Търсене',
  loading: 'Зареждане...',
  noResults: 'Няма резултати',
  success: 'Успех',
  error: 'Грешка',
  warning: 'Предупреждение',
  info: 'Информация',
  confirm: 'Потвърди',
  back: 'Назад',
  next: 'Напред',
  submit: 'Изпрати',
  reset: 'Нулиране',
  select: 'Избери',
  upload: 'Качи',
  download: 'Изтегли',
  view: 'Преглед',
  preview: 'Преглед',
  print: 'Печат',
  export: 'Експорт',
  import: 'Импорт',
  settings: 'Настройки',
  help: 'Помощ',
  logout: 'Изход',
  login: 'Вход',
  register: 'Регистрация',
  required: 'Задължително',
  optional: 'Незадължително',
  all: 'Всички',
  none: 'Няма',
  noName: 'Без име',
  noDescription: 'Без описание',
  description: 'Описание',
  saving: 'Запазване...',
  areYouSure: 'Сигурни ли сте?',
  thisActionCannot: 'Това действие не може да бъде отменено',
  errorOccurred: 'Възникна грешка',
  confirmDelete: 'Потвърдете изтриването',
  copy: 'Копирай',
  open: 'Отвори',
  close: 'Затвори',
  more: 'Още',
  yes: 'Да',
  no: 'Не',
  actions: 'Действия',
  apply: 'Приложи',
  confirm_delete: 'Сигурни ли сте, че искате да изтриете това?',
  confirm_reset: 'Сигурни ли сте, че искате да нулирате това?',
  continue: 'Продължи',
  continue_anyway: 'Продължи въпреки това',
  discard: 'Отхвърли',
  discard_changes: 'Отхвърли промените',
  dark_mode: 'Тъмен режим',
  light_mode: 'Светъл режим',
  system_theme: 'Системна тема',
  copy_to_clipboard: 'Копирай в клипборда',
  copied_to_clipboard: 'Копирано в клипборда',
  search_placeholder: 'Търсене...',
  
  // Add missing properties
  processing: 'Обработка...',
  selectOne: 'Избери един',
  new: 'Нов',
  chooseFile: 'Избери файл',
  created: 'Създаден',
  updated: 'Обновен',
  save_changes: 'Запази промените',
  confirmDeleteText: 'Това действие не може да бъде отменено.',
  viewImage: 'Преглед на изображение',
  selectDate: 'Избери дата',
  allProducts: 'Всички продукти',
  itemsSelected: 'избрани елемента',
  clear: 'Изчисти',
  clearFilters: 'Изчисти филтрите',
  noDataAvailable: 'Няма налични данни',
  today: 'Днес',
  day: 'Ден',
  week: 'Седмица',
  month: 'Месец',
  year: 'Година',
  or: 'или',
  and: 'и',
  prev: 'Предишен',
  configuration: 'Конфигурация',
  pageOf: 'Страница {current} от {total}',
  showingItems: 'Показване от {start} до {end} от {total} елемента',
  account: 'Акаунт',
  newOffer: 'Нова оферта',
  newClient: 'Нов клиент',
  newProduct: 'Нов продукт',
  manageAccount: 'Управление на акаунт',
  confirmation: 'Потвърждение',
  confirmationQuestion: 'Сигурни ли сте, че искате да продължите?',
  expandAll: 'Разгъни всички',
  collapseAll: 'Свий всички',
  welcome: 'Добре дошли',
  unauthorized: 'Неоторизиран достъп',
  retry: 'Опитай отново',
  home: 'Начало',
  templates: 'Шаблони',
  navigation: 'Навигация',
  copied: 'Копирано'
};
