
export const common = {
  back: 'Назад',
  save: 'Запази',
  cancel: 'Отказ',
  delete: 'Изтрий',
  edit: 'Редактирай',
  create: 'Създай',
  search: 'Търси',
  add: 'Добави',
  remove: 'Премахни',
  confirm: 'Потвърди',
  success: 'Успешно',
  error: 'Грешка',
  warning: 'Предупреждение',
  info: 'Информация',
  continue: 'Продължи',
  next: 'Напред',
  previous: 'Назад',
  submit: 'Изпрати',
  reset: 'Нулиране',
  apply: 'Приложи',
  all: 'Всички',
  select: 'Избери',
  loading: 'Зареждане...',
  noResults: 'Няма намерени резултати',
  required: 'Задължително',
  optional: 'Опционално',
  
  // Add missing fields to make this compatible with CommonTranslations
  offerForge: 'OfferForge',
  saving: 'Запазване...',
  close: 'Затвори',
  preview: 'Преглед',
  previewOffer: 'Преглед на оферта',
  backToEdit: 'Назад към редакция',
  yes: 'Да',
  no: 'Не',
  name: 'Име',
  login: 'Вход',
  logout: 'Изход',
  register: 'Регистрация',
  upload: 'Качи',
  export: 'Експорт',
  import: 'Импорт',
  actions: 'Действия',
  description: 'Описание',
  details: 'Детайли',
  print: 'Печат',
  copy: 'Копирай',
  download: 'Изтегли',
  share: 'Сподели',
  options: 'Опции',
  settings: 'Настройки',
  profile: 'Профил',
  account: 'Акаунт',
  help: 'Помощ',
  about: 'За нас',
  contact: 'Контакт',
  privacyPolicy: 'Политика за поверителност',
  termsOfService: 'Условия за ползване',
  copyright: 'Авторско право',
  language: 'Език',
  currency: 'Валута',
  theme: 'Тема',
  light: 'Светла',
  dark: 'Тъмна',
  system: 'Системна',
  areYouSure: 'Сигурни ли сте?',
  thisActionCannot: 'Това действие не може да бъде отменено',
  default: 'По подразбиране',
  id: 'ИД',
  date: 'Дата',
  time: 'Време',
  amount: 'Сума',
  total: 'Общо',
  subtotal: 'Междинна сума',
  tax: 'Данък',
  discount: 'Отстъпка',
  quantity: 'Количество',
  price: 'Цена',
  status: 'Статус',
  type: 'Тип',
  confirmation: 'Потвърждение',
  processing: 'Обработка',
  comingSoon: 'Очаквайте скоро',
  featureInDevelopment: 'Тази функционалност е в процес на разработка',
  step: 'Стъпка',
  of: 'от',
  finish: 'Завърши',
  unauthorized: 'Неоторизиран',
  manageAccount: 'Управление на акаунт',
  home: 'Начало',
  collapseAll: 'Свий всички',
  expandAll: 'Разгъни всички',
  view: 'Преглед',
  update: 'Обнови',
  viewAll: 'Виж всички',
  welcome: 'Добре дошли',
  dashboard: 'Табло',
  newOffer: 'Нова оферта',
  newClient: 'Нов клиент',
  newProduct: 'Нов продукт',
  templates: 'Шаблони',
  navigation: 'Навигация',
  noName: 'Без име',
  retry: 'Опитай отново',
  
  // Color preset translations
  colorPresets: 'Цветови присети',
  applyPreset: 'Приложи присет',
  customColors: 'Персонализирани цветове'
};
