
import { CompanyTranslations } from '@/types/language/company';

export const company: CompanyTranslations = {
  companyInfo: "Информация за компанията",
  companyName: "Име на компанията",
  vatNumber: "ДДС номер",
  address: "Адрес",
  city: "Град",
  postalCode: "Пощенски код",
  country: "Държава",
  phone: "Телефон",
  email: "Имейл",
  website: "Уебсайт",
  logoUrl: "URL адрес на логото",
  description: "Описание",
  contactPerson: "Лице за контакт",
  title: "Заглавие",
  position: "Позиция",
  noCompany: "Няма избрана компания",
  selectFirst: "Моля, изберете компания първо",
  selectCompany: "Изберете компания",
  createCompany: "Създайте компания",
  companyCreated: "Компанията е създадена успешно",
  companyUpdated: "Компанията е актуализирана успешно",
  companyDeleted: "Компанията е изтрита успешно",
  companyDetails: "Детайли за компанията",
  addCompanyLogo: "Добавете лого на компанията",
  logoUploadSuccess: "Логото е качено успешно",
  logoUploadFail: "Неуспешно качване на логото",
  selectPlaceholder: "Изберете компания",
  createNew: "Създай нова компания",
  createFirst: "Създай първа компания",
  useSelector: "Използвайте селектора за компания по-горе за да продължите",
  companySettings: "Настройки на компанията",
  regNumber: "Рег. номер",
  companyInfo_bg: "Информация за компанията (БГ)",
  companyInfo_en: "Информация за компанията (EN)",
  bankInfo: "Банкова информация",
  bankName: "Име на банката",
  bankAccount: "Банкова сметка",
  bankCode: "Банков код",
  swift: "SWIFT",
  iban: "IBAN",
  bankDetails: "Банкови детайли",
  members: "Членове на екипа",
  inviteMembers: "Поканете членове",
  owner: "Собственик",
  admin: "Администратор",
  member: "Член",
  viewer: "Наблюдател",
  companySelected: "Компания избрана",
  companyChanged: "Компанията е променена",
  offerPreparation: "Подготвя се оферта за избраната компания...",
  updatingOffer: "Офертата се актуализира с новата компания...",
  
  // Adding missing placeholders
  vatPlaceholder: "Въведете ДДС номер",
  phonePlaceholder: "Въведете телефонен номер",
  emailPlaceholder: "Въведете имейл адрес",
  websitePlaceholder: "Въведете URL адрес на уебсайт",
  addressPlaceholder: "Въведете адрес",
  cityPlaceholder: "Въведете град",
  countryPlaceholder: "Въведете държава",
  namePlaceholder: "Въведете име на компанията",
  
  // Adding missing buttons and messages
  updateButton: "Обнови компанията",
  create: "Създай компания",
  createButton: "Създай компания",
  manage: "Управление на компании",
  info: "Преглед и редактиране на информацията за компанията",
  
  // Adding missing error and success messages
  error: "Грешка",
  success: "Успех",
  nameRequired: "Името на компанията е задължително",
  createdSuccessfully: "Компанията е създадена успешно",
  
  // Adding the missing property for UserProfileModal
  noCompanies: "Няма намерени компании"
};
