
import { Translations } from '@/types/language';

export const bgTranslations: Translations = {
  offerTitle: 'Офертен ковач',
  common: {
    edit: 'Редактиране',
    preview: 'Преглед',
    previewOffer: 'Преглед на оферта',
    backToEdit: 'Обратно към редактиране',
    save: 'Запази',
    print: 'Печат',
    add: 'Добави',
    currency: 'Валута',
    loading: 'Зареждане...',
    processing: 'Обработка...',
    error: 'Възникна грешка',
    success: 'Успешно',
    account: 'Акаунт',
    settings: 'Настройки',
    comingSoon: 'Очаквайте скоро',
    featureInDevelopment: 'Тази функционалност е в процес на разработка.'
  },
  auth: {
    signIn: 'Вход',
    signUp: 'Регистрация',
    signOut: 'Изход',
    signOutSuccess: 'Излязохте успешно от акаунта си',
    signOutError: 'Грешка при излизане от акаунта',
    email: 'Имейл',
    password: 'Парола',
    forgotPassword: 'Забравена парола?',
    noAccount: 'Нямате акаунт?',
    hasAccount: 'Вече имате акаунт?',
    resetPassword: 'Нулиране на парола',
    name: 'Име',
    loginSuccess: 'Успешен вход',
    registerSuccess: 'Успешна регистрация',
    checkEmail: 'Моля, проверете имейла си за потвърждение на акаунта',
    error: 'Грешка при автентикация',
    processing: 'Обработка...',
    loginButton: 'Вход',
    registerButton: 'Регистрация',
    loginTitle: 'Вход в акаунта',
    registerTitle: 'Създаване на нов акаунт',
    loginDescription: 'Въведете данните си за достъп до акаунта',
    registerDescription: 'Попълнете формата, за да създадете акаунт',
    namePlaceholder: 'Въведете вашето име',
    emailPlaceholder: 'Въведете вашия имейл',
    passwordPlaceholder: 'Въведете вашата парола',
    needAccount: 'Нуждаете се от акаунт?',
    haveAccount: 'Вече имате акаунт?',
    welcomeTitle: 'Добре дошли в Офертен ковач',
    welcomeSubtitle: 'Създавайте професионални оферти лесно'
  },
  user: {
    profile: 'Моят профил',
    editProfile: 'Редактиране на профил',
    name: 'Име',
    email: 'Имейл',
    password: 'Парола',
    confirmPassword: 'Потвърдете паролата',
    updateProfile: 'Обновяване на профил'
  },
  company: {
    info: 'Информация за фирмата',
    name: 'Име на фирмата',
    vatNumber: 'ДДС Номер',
    address: 'Адрес',
    city: 'Град',
    country: 'Държава',
    phone: 'Телефон',
    email: 'Имейл',
    website: 'Уебсайт',
    logo: 'Лого',
    uploadLogo: 'Качване на лого',
    manage: 'Управление на фирмата',
    selectFirst: 'Моля, първо изберете фирма',
    create: 'Създаване на фирма',
    createButton: 'Създай',
    edit: 'Редактиране на фирма',
    update: 'Обновяване на фирма',
    updateButton: 'Обнови',
    delete: 'Изтриване на фирма',
    deleteConfirm: 'Сигурни ли сте, че искате да изтриете тази фирма?',
    error: 'Грешка при фирмата',
    success: 'Успешно действие',
    nameRequired: 'Името на фирмата е задължително',
    createdSuccessfully: 'Фирмата беше създадена успешно',
    createNew: 'Създаване на нова фирма',
    createFirst: 'Моля, създайте първата си фирма',
    selectPlaceholder: 'Изберете фирма',
    namePlaceholder: 'Въведете име на фирмата',
    vatPlaceholder: 'Въведете ДДС номер',
    addressPlaceholder: 'Въведете адрес на фирмата',
    cityPlaceholder: 'Въведете град',
    countryPlaceholder: 'Въведете държава',
    phonePlaceholder: 'Въведете телефонен номер',
    emailPlaceholder: 'Въведете имейл адрес',
    websitePlaceholder: 'Въведете уебсайт URL'
  },
  client: {
    info: 'Информация за клиента',
    name: 'Име на клиента',
    vatNumber: 'ДДС Номер',
    address: 'Адрес',
    email: 'Имейл',
    contactPerson: 'Лице за контакт',
    city: 'Град',
    country: 'Държава',
    phone: 'Телефон'
  },
  clientInfo: {
    title: 'Информация за клиента',
    name: 'Име на клиента',
    vatNumber: 'ДДС Номер',
    address: 'Адрес',
    contactPerson: 'Лице за контакт',
    city: 'Град',
    country: 'Държава',
    email: 'Имейл',
    phone: 'Телефон'
  },
  companyInfo: {
    title: 'Информация за фирмата',
    name: 'Име на фирмата',
    vatNumber: 'ДДС Номер',
    address: 'Адрес',
    city: 'Град',
    country: 'Държава',
    phone: 'Телефон',
    email: 'Имейл',
    website: 'Уебсайт',
    logo: 'Лого',
    uploadLogo: 'Качване на лого'
  },
  offer: {
    details: 'Детайли на офертата',
    number: 'Номер на офертата',
    date: 'Дата',
    validUntil: 'Валидна до',
    notes: 'Бележки',
    terms: 'Общи условия',
    status: 'Статус',
    statuses: {
      draft: 'Чернова',
      sent: 'Изпратена',
      accepted: 'Приета',
      rejected: 'Отхвърлена'
    },
    offerLabel: 'ОФЕРТА',
    toLabel: 'До',
    attention: 'Внимание:',
    item: 'Артикул',
    partNo: 'Парт №',
    qty: 'Кол.',
    unitPrice: 'Ед. цена',
    total: 'Общо',
    vatIncluded: 'ДДС е включен в цената',
    vatExcluded: 'ДДС не е включен в цената',
    thankYou: 'Благодарим ви за доверието!',
    language: 'Език на офертата',
    languageOptions: {
      bulgarian: 'Български',
      english: 'Английски'
    }
  },
  offerDetails: {
    title: 'Детайли на офертата',
    offerNumber: 'Номер на офертата',
    date: 'Дата',
    validUntil: 'Валидна до',
    showPartNumber: 'Показвай номер на част',
    includeVat: 'Включи ДДС',
    vatRate: 'ДДС ставка (%)',
    transportCost: 'Транспортни разходи',
    otherCosts: 'Други разходи',
    notes: 'Бележки',
    notesPlaceholder: 'Добавете допълнителни бележки или коментари към офертата...',
    language: 'Език'
  },
  products: {
    title: 'Продукти',
    name: 'Име на продукта',
    description: 'Описание',
    price: 'Цена',
    quantity: 'Количество',
    vat: 'ДДС (%)',
    vatIncluded: 'Включен ДДС',
    total: 'Общо',
    addProduct: 'Добави продукт',
    removeProduct: 'Премахни продукт',
    noProducts: 'Все още няма добавени продукти.',
    productName: 'Име на продукта',
    partNumber: 'Номер на част',
    unitPrice: 'Единична цена'
  },
  totals: {
    subtotal: 'Междинна сума',
    vat: 'ДДС',
    transport: 'Транспорт',
    otherCosts: 'Други разходи',
    totalAmount: 'Обща сума'
  }
};
