
export const offer = {
  title: "Оферта",
  offerTitle: "Създаване на оферта",
  details: "Детайли на офертата",
  offerNumber: "Номер на офертата",
  offerDate: "Дата на офертата",
  dueDate: "Валидна до",
  currency: "Валута",
  offerLanguage: "Език на офертата",
  subject: "Относно",
  notes: "Бележки",
  termsAndConditions: "Условия",
  status: "Статус",
  accepted: "Приета",
  rejected: "Отхвърлена",
  pending: "В очакване",
  draft: "Чернова",
  offerPreview: "Преглед на офертата",
  createOffer: "Създаване на оферта",
  templates: {
    title: "Шаблони",
    createNew: "Създай нов шаблон",
    availableTemplates: "Налични шаблони",
    noTemplatesFound: "Няма намерени шаблони. Създайте вашия първи шаблон!",
    noDescription: "Няма предоставено описание",
    confirmDelete: "Сигурни ли сте, че искате да изтриете този шаблон?",
    templateDeleted: "Шаблонът беше изтрит успешно"
  },
};
