
export const offer = {
  title: "Оферта",
  offerTitle: "Създаване на оферта",
  details: "Детайли на офертата",
  offerNumber: "Номер на офертата",
  offerDate: "Дата на офертата",
  dueDate: "Валидна до",
  currency: "Валута",
  offerLanguage: "Език на офертата",
  subject: "Относно",
  notes: "Бележки",
  termsAndConditions: "Условия",
  status: "Статус",
  accepted: "Приета",
  rejected: "Отхвърлена",
  pending: "В очакване",
  draft: "Чернова",
  offerPreview: "Преглед на офертата",
  createOffer: "Създаване на оферта",
  languageOptions: {
    bulgarian: "Български",
    english: "Английски"
  },
  vatIncluded: "ДДС включено",
  vatExcluded: "ДДС не е включено",
  offerLabel: "ОФЕРТА",
  toLabel: "ДО",
  attention: "На вниманието на",
  item: "Артикул",
  partNo: "Номер",
  qty: "Кол.",
  unitPrice: "Ед. цена",
  total: "Общо",
  thankYou: "Благодарим Ви за доверието!",
  validUntil: "Валидна до",
  templates: {
    title: "Шаблони",
    createNew: "Създай нов шаблон",
    availableTemplates: "Налични шаблони",
    noTemplatesFound: "Няма намерени шаблони. Създайте вашия първи шаблон!",
    noDescription: "Няма предоставено описание",
    confirmDelete: "Сигурни ли сте, че искате да изтриете този шаблон?",
    templateDeleted: "Шаблонът беше изтрит успешно",
    defaultTemplates: "Стандартни шаблони",
    userTemplates: "Потребителски шаблони",
    description: "Описание",
    useTemplate: "Използвай шаблона",
    createFromCurrent: "Създай от текущата",
    templateName: "Име на шаблона",
    saveAsTemplate: "Запази като шаблон",
    templateSaved: "Шаблонът е запазен",
    noTemplates: "Няма шаблони",
    deleteTemplate: "Изтрий шаблона"
  },
};
