
export const offerDetails = {
  title: "Детайли на офертата",
  description: "Конфигурирайте детайлите на вашата оферта",
  offerNumber: "Номер на офертата",
  offerNumberInfo: "Този номер се генерира автоматично",
  date: "Дата",
  validUntil: "Валидна до",
  validUntilPlaceholder: "Изберете дата на валидност",
  showPartNumber: "Покажи продуктов код",
  includeVat: "Включи ДДС",
  vatIncluded: "Цените включват ДДС",
  vatExcluded: "Цените не включват ДДС",
  vatRate: "ДДС ставка (%)",
  transportCost: "Транспортни разходи",
  transportCostPlaceholder: "0.00",
  otherCosts: "Други разходи",
  otherCostsPlaceholder: "0.00",
  notes: "Бележки",
  notesPlaceholder: "Допълнителна информация или условия",
  language: "Език на офертата",
  currency: "Валута",
  // New translations
  specialDiscounts: "Специални отстъпки",
  addDiscount: "Добави отстъпка",
  discountType: "Тип отстъпка",
  discountAmount: "Размер на отстъпката",
  discountDescription: "Описание на отстъпката",
  percentageDiscount: "Процентна отстъпка",
  fixedDiscount: "Фиксирана сума",
  showDigitalSignature: "Покажи дигитален подпис",
  customFooterText: "Допълнителен текст в края",
  customFooterTextPlaceholder: "Въведете условия или допълнителен текст"
};
