
export const offer = {
  title: 'Оферта',
  createOffer: 'Създаване на оферта',
  offerDetails: 'Детайли на офертата',
  offerPreview: 'Преглед на офертата',
  details: 'Детайли',
  backToOffer: "Обратно към офертата",
  number: "Номер",
  date: "Дата",
  validUntil: "Валидна до",
  notes: "Бележки",
  terms: "Условия",
  status: "Статус",
  statuses: {
    draft: "Чернова",
    sent: "Изпратена",
    accepted: "Приета",
    rejected: "Отхвърлена"
  },
  offerLabel: "Оферта",
  toLabel: "До",
  attention: "На вниманието на",
  item: "Артикул",
  partNo: "Арт. №",
  qty: "К-во",
  unitPrice: "Ед. цена",
  total: "Общо",
  vatIncluded: "С ДДС",
  vatExcluded: "Без ДДС",
  thankYou: "Благодарим Ви за бизнеса",
  language: "Език",
  languageOptions: {
    bulgarian: "Български",
    english: "Английски"
  },
  templates: {
    title: 'Шаблони',
    description: 'Описание на шаблона',
    useTemplate: 'Използвай шаблон',
    createFromCurrent: 'Създай от текущата оферта',
    templateName: 'Име на шаблона',
    saveAsTemplate: 'Запази като шаблон',
    templateSaved: 'Шаблонът е запазен',
    noTemplates: 'Няма шаблони',
    confirmDelete: 'Потвърди изтриване',
    deleteTemplate: 'Изтрий шаблон',
    templateDeleted: 'Шаблонът е изтрит',
    defaultTemplates: 'Стандартни шаблони',
    userTemplates: 'Създадени от потребителя',
    createNew: 'Създай нов шаблон',
    availableTemplates: 'Налични шаблони',
    noTemplatesFound: 'Няма намерени шаблони.',
    noDescription: 'Няма описание',
  },
};
