import { SettingsTranslations } from '@/types/language/settings';

export const settings: SettingsTranslations = {
  title: "Настройки",
  subtitle: "Управление на настройките на системата",
  general: "Общи",
  appearance: "Външен вид",
  layout: "Подредба",
  content: "Съдържание",
  template: "Шаблон",
  details: "Детайли",
  templates: {
    classic: "Класически",
    modernDark: "Модерен Тъмен",
    gradient: "Градиент",
    businessPro: "Бизнес Про",
    selectDesign: "Избери дизайн на шаблона"
  },
  offerTemplates: "Шаблони за оферти",
  templatesDescription: "Управлявайте вашите шаблони за оферти",
  preview: "Преглед",
  templateName: "Име на шаблона",
  templateNamePlaceholder: "Въведете име на шаблона",
  templateDescription: "Описание",
  templateDescriptionPlaceholder: "Въведете описание на шаблона",
  templateLanguage: "Език на шаблона",
  selectLanguage: "Изберете език",
  primaryColor: "Основен цвят",
  secondaryColor: "Вторичен цвят",
  textColor: "Цвят на текста",
  fontFamily: "Шрифт",
  selectFont: "Изберете шрифт",
  fontSize: "Размер на шрифта",
  selectFontSize: "Изберете размер на шрифта",
  roundedCorners: "Заоблени ъгли",
  roundedCornersDescription: "Използвайте заоблени ъгли за елементите",
  showLogo: "Покажи логото",
  showLogoDescription: "Покажи логото на компанията",
  logoPosition: "Позиция на логото",
  selectLogoPosition: "Изберете позиция на логото",
  compactMode: "Компактен режим",
  compactModeDescription: "Намалява разстоянията и размерите на шрифтовете",
  fullWidth: "Пълна ширина",
  fullWidthDescription: "Използвай пълната ширина за офертата",
  borderless: "Без рамки",
  borderlessDescription: "Премахни рамките на елементите",
  useShadows: "Използвай сенки",
  useShadowsDescription: "Добави сенки към елементите",
  boldPrices: "Удебелени цени",
  boldPricesDescription: "Показвай цените с удебелен шрифт",
  alternateRowColors: "Редуващи се цветове",
  alternateRowColorsDescription: "Използвай редуващи се цветове за редовете в таблицата",
  showLineNumbers: "Покажи номера на редовете",
  showLineNumbersDescription: "Показвай номера на редовете в таблицата с продукти",
  showFooter: "Покажи футър",
  showFooterDescription: "Показвай текст във футъра",
  footerText: "Текст на футъра",
  showBankDetails: "Покажи банкови данни",
  showBankDetailsDescription: "Показвай банкова информация във футъра",
  showSignatureArea: "Покажи място за подпис",
  showSignatureAreaDescription: "Включи място за подпис",
  signatureText: "Текст за подпис",
  useQRCode: "Използвай QR код",
  useQRCodeDescription: "Включи QR код за дигитална референция",
  showCompanySlogan: "Покажи слоган на компанията",
  showCompanySloganDescription: "Показвай слогана на компанията в хедъра",
  companyNameSize: "Размер на името на компанията",
  selectSize: "Изберете размер",
  showOfferLabel: "Покажи етикет ОФЕРТА",
  showOfferLabelDescription: "Показвай етикет 'ОФЕРТА' в хедъра",
  updateTemplate: "Обнови шаблона",
  saveTemplate: "Запази шаблона",
  templateSaved: "Шаблонът е успешно запазен",
  small: "Малък",
  medium: "Среден",
  large: "Голям",
  left: "Ляво",
  center: "Център",
  right: "Дясно",
  
  // Additional settings required by the interface
  bankDetails: "Банкови детайли",
  bankName: "Име на банката",
  bankNamePlaceholder: "Въведете име на банката",
  iban: "IBAN",
  ibanPlaceholder: "Въведете IBAN",
  swift: "SWIFT",
  swiftPlaceholder: "Въведете SWIFT код",
  additionalInfo: "Допълнителна информация",
  additionalInfoPlaceholder: "Въведете допълнителна информация",
  usePrefix: "Използвай префикс",
  usePrefixDescription: "Използвай префикс за номерата на офертите",
  prefix: "Префикс",
  prefixDescription: "Префикс за номерата на офертите",
  suffixYear: "Добавяне на година",
  suffixYearDescription: "Добави годината към номерата на офертите",
  defaultVatRate: "Стандартна ставка на ДДС",
  defaultVatRateDescription: "Задай стандартна ставка на ДДС за офертите",
  newTemplate: "Нов шаблон",
  createTemplate: "Създай шаблон",
  editTemplate: "Редактирай шаблон",
  viewTemplate: "Преглед на шаблон",
  defaultTemplatesDescription: "Стандартни шаблони",
  noTemplates: "Няма шаблони",
  createNewTemplate: "Създай нов шаблон",
  userTemplates: "Потребителски шаблони",
  sampleTemplates: "Примерни шаблони",
  confirmDeleteTemplate: "Наистина ли искате да изтриете този шаблон?",
  setAsDefault: "Задай като основен",
  default: "Основен",
  templateCreated: "Шаблонът е създаден успешно",
  templateUpdated: "Шаблонът е обновен успешно",
  defaultTemplateSet: "Шаблонът е зададен като основен",
  setDefaultFailed: "Неуспешно задаване на основен шаблон",
  saveTemplateFailed: "Неуспешно запазване на шаблона",
  templateDeleted: "Шаблонът е изтрит успешно",
  deleteTemplateFailed: "Неуспешно изтриване на шаблона",
  useTemplate: "Използвай шаблона",
  showUserTemplatesOnly: "Покажи само потребителски шаблони",
  
  // Custom units settings
  customUnits: "Персонализирани мерни единици",
  customUnitsDescription: "Управлявайте вашите персонализирани мерни единици",
  unitNameBg: "Име на единицата (Български)",
  unitNameEn: "Име на единицата (Английски)",
  unitNamePlaceholderBg: "Въведете име на единицата на български",
  unitNamePlaceholderEn: "Въведете име на единицата на английски",
  addUnit: "Добави единица",
  existingUnits: "Съществуващи единици",
  noCustomUnits: "Няма персонализирани единици",
  unitAdded: "Единицата е добавена",
  unitAddedSuccess: "Единицата е добавена успешно",
  unitDeleted: "Единицата е изтрита",
  unitDeletedSuccess: "Единицата е изтрита успешно",
  errorLoadingSettings: "Грешка при зареждане на настройките",
  errorSavingSettings: "Грешка при запазване на настройките",
  unitAddError: "Грешка при добавяне на единицата",
  unitDeleteError: "Грешка при изтриване на единицата",
  validationError: "Грешка при валидация",
  unitNameRequired: "Името на единицата е задължително",
  settingsSaved: "Настройките са запазени успешно",
  offerSettings: "Настройки на офертата",
  noTemplateSelected: "Няма избран шаблон",
  
  // New properties for template settings
  basicInformation: "Основна информация",
  description: "Описание",
  header: "Хедър",
  footer: "Футър",
  appearanceSettings: "Настройки на външния вид",
  pickColor: "Избери цвят",
  headerSettings: "Настройки на хедъра",
  showCompanyLogo: "Покажи логото на компанията",
  showCompanyName: "Покажи името на компанията",
  useGradient: "Използвай градиент за фона",
  contentSettings: "Настройки на съдържанието",
  showProductDescription: "Покажи описание на продуктите",
  showPartNumbers: "Покажи номера на частите",
  footerTextPlaceholder: "Въведете текст за футъра",
  footerTextDescription: "Текст за показване във футъра",
  footerSettings: "Настройки на футъра",
  signatureTextPlaceholder: "Въведете текст за подпис",
  includeSocialMedia: "Включи линкове към социални медии",
  
  // Navigation and editing properties
  edit: "Редактирай",
  resetToDefault: "Възстанови настройките по подразбиране",
  primaryColorLabel: "Основен цвят",
  secondaryColorLabel: "Вторичен цвят",
  textColorLabel: "Цвят на текста",
  borderColorLabel: "Цвят на рамките",
  backgroundColorLabel: "Цвят на фона",
  tableHeaderColorLabel: "Цвят на хедъра на таблицата",
  tableRowAlternateColorLabel: "Цвят на редуващите се редове",
  buttonColorLabel: "Цвят на бутоните",
  fontFamilyLabel: "Шрифт",
  fontSizeLabel: "Размер на шрифта",
  headerBackgroundColorLabel: "Цвят на фона на хедъра",
  headerTextColorLabel: "Цвят на текста в хедъра",
  tableBorderStyleLabel: "Стил на рамките на таблицата",
  tableBorderWidthLabel: "Дебелина на рамките",
  tableBorderColorLabel: "Цвят на рамките на таблицата",
  footerBackgroundColorLabel: "Цвят на фона на футъра",
  footerTextColorLabel: "Цвят на текста във футъра",
  fullWidthLabel: "Пълна ширина",
  borderRadiusLabel: "Радиус на ъглите",
  paddingLabel: "Вътрешно отстояние",
};
