
import { SettingsTranslations } from '@/types/language/settings';

export const settings: SettingsTranslations = {
  title: "Настройки",
  general: "Общи",
  appearance: "Външен вид",
  layout: "Подредба",
  content: "Съдържание",
  template: "Шаблон",
  details: "Детайли",
  templates: {
    classic: "Класически",
    modernDark: "Модерен Тъмен",
    gradient: "Градиент",
    businessPro: "Бизнес Про",
    selectDesign: "Избери дизайн на шаблона"
  },
  offerTemplates: "Шаблони за оферти",
  templatesDescription: "Управлявайте вашите шаблони за оферти",
  preview: "Преглед",
  templateName: "Име на шаблона",
  templateNamePlaceholder: "Въведете име на шаблона",
  templateDescription: "Описание",
  templateDescriptionPlaceholder: "Въведете описание на шаблона",
  templateLanguage: "Език на шаблона",
  selectLanguage: "Изберете език",
  primaryColor: "Основен цвят",
  secondaryColor: "Вторичен цвят",
  textColor: "Цвят на текста",
  fontFamily: "Шрифт",
  selectFont: "Изберете шрифт",
  fontSize: "Размер на шрифта",
  selectFontSize: "Изберете размер на шрифта",
  roundedCorners: "Заоблени ъгли",
  roundedCornersDescription: "Използвайте заоблени ъгли за елементите",
  showLogo: "Покажи логото",
  showLogoDescription: "Покажи логото на компанията",
  logoPosition: "Позиция на логото",
  selectLogoPosition: "Изберете позиция на логото",
  compactMode: "Компактен режим",
  compactModeDescription: "Намалява разстоянията и размерите на шрифтовете",
  fullWidth: "Пълна ширина",
  fullWidthDescription: "Използвай пълната ширина за офертата",
  borderless: "Без рамки",
  borderlessDescription: "Премахни рамките на елементите",
  useShadows: "Използвай сенки",
  useShadowsDescription: "Добави сенки към елементите",
  boldPrices: "Удебелени цени",
  boldPricesDescription: "Показвай цените с удебелен шрифт",
  alternateRowColors: "Редуващи се цветове",
  alternateRowColorsDescription: "Използвай редуващи се цветове за редовете в таблицата",
  showLineNumbers: "Покажи номера на редовете",
  showLineNumbersDescription: "Показвай номера на редовете в таблицата с продукти",
  showFooter: "Покажи футър",
  showFooterDescription: "Показвай текст във футъра",
  footerText: "Текст на футъра",
  showBankDetails: "Покажи банкови данни",
  showBankDetailsDescription: "Показвай банкова информация във футъра",
  showSignatureArea: "Покажи място за подпис",
  showSignatureAreaDescription: "Включи място за подпис",
  signatureText: "Текст за подпис",
  useQRCode: "Използвай QR код",
  useQRCodeDescription: "Включи QR код за дигитална референция",
  showCompanySlogan: "Покажи слоган на компанията",
  showCompanySloganDescription: "Показвай слогана на компанията в хедъра",
  companyNameSize: "Размер на името на компанията",
  selectSize: "Изберете размер",
  showOfferLabel: "Покажи етикет ОФЕРТА",
  showOfferLabelDescription: "Показвай етикет 'ОФЕРТА' в хедъра",
  updateTemplate: "Обнови шаблона",
  saveTemplate: "Запази шаблона",
  templateSaved: "Шаблонът е успешно запазен",
  small: "Малък",
  medium: "Среден",
  large: "Голям",
  left: "Ляво",
  center: "Център",
  right: "Дясно"
};
