
export const offerDraft = {
  draftInProgress: "Чернова в процес на работа",
  draftSaved: "Черновата е запазена",
  draftSavedDescription: "Вашата чернова е запазена успешно",
  draftSaveError: "Грешка при запазване на черновата",
  draftSavedToLocalStorage: "Черновата е запазена локално като резервно копие.",
  autoSaveDisabled: "Автоматичното запазване е изключено",
  autoSaveEnabled: "Автоматичното запазване е включено",
  noContentToSave: "Няма съдържание за запазване",
  addContentToSave: "Добавете съдържание, за да запазите черновата",
  returnToDraft: "Продължете работата си от запазената чернова",
  draftLoaded: "Черновата е заредена",
  draftRestoredDescription: "Успешно възстановихме вашата чернова",
  lastSaved: "Последно запазено преди {time}",
  notSavedYet: "Още не е запазено",
  saving: "Запазване...",
  saved: "Запазено",
  unsavedChanges: "Незапазени промени",
  saveManually: "Запази ръчно",
  disableAutoSave: "Изключи автоматичното запазване",
  enableAutoSave: "Включи автоматичното запазване",
  draftStatus: "Чернова на оферта",
  continueWorking: "Продължете работата си по черновата на офертата",
  openDraft: "Отвори черновата"
};
