
export const offerProducts = {
  addProducts: "Добави продукти",
  addNewProduct: "Добави нов продукт",
  noProductsAdded: "Няма добавени продукти",
  productName: "Име на продукта",
  quantity: "Количество",
  unitPrice: "Единична цена",
  totalPrice: "Обща цена",
  removeProduct: "Премахни продукт",
  editProduct: "Редактирай продукт",
  productDetails: "Детайли на продукта",
  productNamePlaceholder: "Въведете име на продукта",
  quantityPlaceholder: "Въведете количество",
  unitPricePlaceholder: "Въведете единична цена",
  saveProduct: "Запази продукт",
  showPartNumber: "Покажи партиден номер",
  partNumber: "Партиден номер",
  includeVat: "Включи ДДС",
  vatRate: "ДДС ставка",
  transportCost: "Транспортни разходи",
  otherCosts: "Други разходи",
  total: "Общо",
  subtotal: "Междинна сума",
  vat: "ДДС",
  totalAmount: "Обща сума",
  item: "Позиция",
  qty: "Бр.",
  productDescription: "Описание на продукта",
  descriptionPlaceholder: "Въведете описание на продукта",
  unit: "Единица",
  selectUnit: "Изберете единица",
  noUnit: "Без единица",
  productImage: "Изображение на продукта",
  uploadImage: "Качи изображение",
  imageUploaded: "Изображението е качено успешно",
  imageDeleted: "Изображението е изтрито успешно",
  noImage: "Няма изображение"
};
