
export const offerTemplates = {
  createTemplate: "Създай темплейт",
  saveAsTemplate: "Запази като шаблон",
  applyTemplate: "Приложи шаблон",
  noTemplatesFound: "Не са намерени шаблони",
  templateApplied: "Шаблонът е приложен успешно",
  templateName: "Име на шаблона",
  templateDescription: "Описание на шаблона",
  templateNamePlaceholder: "Въведете име на шаблона",
  templateDescriptionPlaceholder: "Въведете описание на шаблона",
  applyThisTemplate: "Приложи този шаблон",
  templateCreated: "Шаблонът е създаден успешно",
  templateUpdated: "Шаблонът е обновен успешно",
  templateDeleted: "Шаблонът е изтрит успешно",
  templateSaved: "Шаблонът е запазен успешно",
  templateSaveError: "Грешка при запазване на шаблона",
  defaultTemplate: "По подразбиране",
  setDefaultTemplate: "Задай като шаблон по подразбиране",
  resetToDefault: "Възстанови по подразбиране",
  customizeTemplate: "Персонализиране на шаблон",
  sectionSettings: "Настройки на секцията",
  headerSettings: "Настройки на заглавната част",
  footerSettings: "Настройки на долната част",
  companyLogo: "Лого на компанията",
  companySlogan: "Слоган на компанията",
  clientLogo: "Лого на клиента",
  clientDetails: "Детайли за клиента",
  showClientLogo: "Покажи лого на клиента",
  showClientDetails: "Покажи детайли за клиента",
  productTableSettings: "Настройки на таблицата с продукти",
  showProductImage: "Покажи изображение на продукта",
  showProductDescription: "Покажи описание на продукта",
  totalSettings: "Настройки на общата сума",
  showTotal: "Покажи обща сума",
  termsAndConditions: "Общи условия",
  thankYouMessage: "Съобщение за благодарност",
  saveTemplate: "Запази шаблон",
  createOfferTemplate: "Създайте шаблон за оферта",
  manageOfferTemplates: "Управление на шаблони за оферти",
  offerTemplateName: "Име на шаблон за оферта",
  offerTemplateDescription: "Описание на шаблон за оферта",
  fromTemplate: "От шаблон",
  
  // Templates related translations
  templates: {
    title: "Шаблони",
    description: "Управление на вашите шаблони",
    empty: "Няма намерени шаблони",
    create: "Създай шаблон",
    delete: "Изтрий шаблон",
    confirmDelete: "Сигурни ли сте, че искате да изтриете този шаблон?",
    templateDeleted: "Шаблонът е изтрит",
    apply: "Приложи шаблон",
    createNew: "Създай нов шаблон",
    name: "Име на шаблона",
    namePlaceholder: "Въведете име на шаблона",
    descriptionPlaceholder: "Въведете описание на шаблона",
    save: "Запази шаблон",
    cancel: "Отказ",
    saved: "Шаблонът е запазен",
    error: "Грешка при запазване на шаблона",
    defaultTemplates: "Шаблони по подразбиране",
    userTemplates: "Вашите шаблони",
    templateName: "Име на шаблона",
    noTemplates: "Няма намерени шаблони",
    templateSaved: "Шаблонът е запазен",
    useTemplate: "Използвай шаблон",
    createFromCurrent: "Създай от текущия",
    saveAsTemplate: "Запази като шаблон",
    noDescription: "Няма описание",
    availableTemplates: "Налични шаблони",
    noTemplatesFound: "Няма намерени шаблони",
    templatePreview: "Преглед на шаблона",
    setAsDefault: "Задай като шаблон по подразбиране",
    resetToDefault: "Възстанови по подразбиране",
    defaultTemplate: "Шаблон по подразбиране",
    sampleTemplates: "Примерни шаблони",
    textColor: "Цвят на текста",
    backgroundColor: "Цвят на фона",
    designTemplateType: "Дизайн на шаблона",
    designTemplates: {
      classic: "Класически",
      modernDark: "Модерен тъмен",
      gradient: "Градиент",
      businessPro: "Бизнес Про",
    }
  }
};
