
export const offerBase = {
  createOffer: "Създай оферта",
  offerDetails: "Детайли на офертата",
  companyInfo: "Информация за компанията",
  clientInfo: "Информация за клиента",
  productsAndServices: "Продукти и услуги",
  previewAndSave: "Преглед и запазване",
  previewAndFinish: "Преглед и финализиране",
  offerName: "Име на офертата",
  offerNumber: "Номер на офертата",
  offerDate: "Дата на офертата",
  date: "Дата",
  validUntil: "Валидна до",
  currency: "Валута",
  notes: "Бележки",
  offerLanguage: "Език на офертата",
  bulgarian: "Български",
  english: "Английски",
  offerNamePlaceholder: "Въведете име на офертата",
  header: "Заглавие",
  fromCompany: "От компания",
  toCompany: "До компания",
  reference: "Референция",
  toLabel: "До",
  attention: "Внимание",
  bgn: "ЛВ",
  eur: "EUR",
  usd: "USD",
  cancel: "Отказ",
  
  // Additional properties to match interface
  previewTitle: "Преглед",
  previewDescription: "Преглед на вашата оферта преди запазване",
  saveOffer: "Запази оферта",
  confirmSave: "Потвърди запазване",
  saveDescription: "Запазете офертата, за да имате достъп до нея по-късно",
  saveAsTemplate: "Запази като шаблон",
  saveAsDraft: "Запази като чернова",
  saveAsFinalized: "Запази като финализирана",
  savedSuccessfully: "Запазено успешно",
  saveFailed: "Грешка при запазване",
  generatePdf: "Генерирай PDF",
  clearConfirm: "Потвърждение за изчистване",
  fromTemplate: "От шаблон",
  item: "Позиция",
  qty: "Бр.",
  total: "Общо",
  subtotal: "Междинна сума",
  vat: "ДДС",
  totalAmount: "Обща сума",
  
  // Language options
  languageOptions: {
    bulgarian: "Български",
    english: "Английски",
  }
};
