export const offerTemplates = {
  createTemplate: "Създай темплейт",
  saveAsTemplate: "Запази като шаблон",
  deleteTemplate: "Изтрий шаблон",
  applyTemplate: "Приложи шаблон",
  noTemplatesFound: "Не са намерени шаблони",
  templateApplied: "Шаблонът е приложен успешно",
  templateName: "Име на шаблона",
  templateDescription: "Описание на шаблона",
  templateNamePlaceholder: "Въведете име на шаблона",
  templateDescriptionPlaceholder: "Въведете описание на шаблона",
  applyThisTemplate: "Приложи този шаблон",
  templateCreated: "Шаблонът е създаден успешно",
  templateUpdated: "Шаблонът е обновен успешно",
  templateDeleted: "Шаблонът е изтрит успешно",
  templateSaved: "Шаблонът е запазен успешно",
  templateSaveError: "Грешка при запазване на шаблона",
  defaultTemplate: "По подразбиране",
  setDefaultTemplate: "Задай като шаблон по подразбиране",
  resetToDefault: "Възстанови по подразбиране",
  customizeTemplate: "Персонализиране на шаблон",
  sectionSettings: "Настройки на секцията",
  headerSettings: "Настройки на заглавната част",
  footerSettings: "Настройки на долната част",
  companyLogo: "Лого на компанията",
  companySlogan: "Слоган на компанията",
  clientLogo: "Лого на клиента",
  clientDetails: "Детайли за клиента",
  showClientLogo: "Покажи лого на клиента",
  showClientDetails: "Покажи детайли за клиента",
  productTableSettings: "Настройки на таблицата с продукти",
  showProductImage: "Покажи изображение на продукта",
  showProductDescription: "Покажи описание на продукта",
  totalSettings: "Настройки на общата сума",
  showTotal: "Покажи обща сума",
  termsAndConditions: "Общи условия",
  thankYouMessage: "Съобщение за благодарност",
  saveTemplate: "Запази шаблон",
  createOfferTemplate: "Създайте шаблон за оферта",
  manageOfferTemplates: "Управление на шаблони за оферти",
  offerTemplateName: "Име на шаблон за оферта",
  offerTemplateDescription: "Описание на шаблон за оферта",
  fromTemplate: "От шаблон",
  deleteTemplateConfirm: "Сигурни ли сте, че искате да изтриете този шаблон?",
  
  templates: {
    title: "Шаблони",
    description: "Управление на външния вид на офертите",
    primaryColor: "Основен цвят",
    tableHeaderColor: "Цвят на заглавния ред",
    orientation: "Ориентация",
    portrait: "Портретна",
    landscape: "Пейзажна",
    applyChanges: "Приложи промените",
    templateSaved: "Промените са запазени",
    defaultTemplate: "Основен шаблон",
    customizeAppearance: "Персонализиране на изгледа",
    chooseColor: "Изберете цвят"
  }
};
