
export const offerTemplates = {
  templates: {
    title: "Шаблони за оферти",
    description: "Управлявайте вашите персонализирани шаблони за оферти",
    primaryColor: "Основен цвят",
    tableHeaderColor: "Цвят на заглавието на таблицата",
    orientation: "Ориентация",
    portrait: "Портрет",
    landscape: "Пейзаж",
    applyChanges: "Приложи промените",
    templateSaved: "Шаблонът е запазен",
    defaultTemplate: "Стандартен шаблон",
    customizeAppearance: "Персонализирай визията",
    chooseColor: "Избери цвят",
    currentTemplate: "Текущ шаблон",
    chooseTemplate: "Избери шаблон",
    noTemplates: "Няма намерени шаблони",
    overwriteTemplate: "Презаписване на шаблон",
    templateDeleted: "Шаблонът е изтрит",
    chooseDefaultTemplate: "Избери стандартен шаблон",
    templateNameRequired: "Името на шаблона е задължително",
    useTemplate: "Използвай",
    createFromCurrent: "Създай от текущата оферта",
    empty: "Няма шаблони",
    create: "Създай шаблон",
    delete: "Изтрий шаблон",
    confirmDelete: "Сигурни ли сте, че искате да изтриете този шаблон?",
    designTemplates: {
      classic: "Класически",
      modernDark: "Модерен тъмен"
    }
  },
  saveAsTemplate: "Запази като шаблон",
  createTemplate: "Създай шаблон",
  deleteTemplate: "Изтрий шаблон",
  deleteTemplateConfirm: "Сигурни ли сте, че искате да изтриете този шаблон?",
  applyTemplate: "Приложи шаблон",
  noTemplatesFound: "Няма намерени шаблони",
  templateApplied: "Шаблонът е приложен",
  templateName: "Име на шаблон",
  templateDescription: "Описание на шаблон",
  templateNamePlaceholder: "Въведете име на шаблон",
  templateDescriptionPlaceholder: "Въведете описание на шаблон",
  createAndApply: "Създай и приложи",
};
