
export const offerTemplates = {
  templates: {
    title: "Шаблони за оферти",
    description: "Управлявайте вашите персонализирани шаблони за оферти",
    primaryColor: "Основен цвят",
    tableHeaderColor: "Цвят на заглавието на таблицата",
    orientation: "Ориентация",
    portrait: "Портрет",
    landscape: "Пейзаж",
    applyChanges: "Приложи промените",
    customizeAppearance: "Персонализирай визията",
    chooseColor: "Избери цвят",
    templateSaved: "Шаблонът е запазен",
    defaultTemplate: "Стандартен шаблон",
    currentTemplate: "Текущ шаблон",
    chooseTemplate: "Избери шаблон",
    noTemplates: "Няма намерени шаблони",
    overwriteTemplate: "Презаписване на шаблон",
    templateDeleted: "Шаблонът е изтрит",
    chooseDefaultTemplate: "Избери стандартен шаблон",
    templateNameRequired: "Името на шаблона е задължително",
    useTemplate: "Използвай",
    createFromCurrent: "Създай от текущата оферта",
    empty: "Няма шаблони",
    create: "Създай шаблон",
    delete: "Изтрий шаблон",
    confirmDelete: "Сигурни ли сте, че искате да изтриете този шаблон?",
    apply: "Приложи шаблон",
    createNew: "Създай нов шаблон",
    name: "Име на шаблон",
    namePlaceholder: "Въведете име на шаблон",
    descriptionPlaceholder: "Въведете описание на шаблон",
    save: "Запазете шаблон",
    cancel: "Отказ",
    saved: "Шаблонът е запазен",
    error: "Грешка при запазване на шаблона",
    defaultTemplates: "Шаблони по подразбиране",
    userTemplates: "Вашите шаблони",
    templateName: "Име на шаблон",
    saveAsTemplate: "Запази като шаблон",
    noDescription: "Няма описание",
    availableTemplates: "Налични шаблони",
    noTemplatesFound: "Няма намерени шаблони",
    templatePreview: "Преглед на шаблона",
    setAsDefault: "Задай като шаблон по подразбиране",
    resetToDefault: "Възстанови по подразбиране",
    sampleTemplates: "Примерни шаблони",
    textColor: "Цвят на текста",
    backgroundColor: "Цвят на фона",
    designTemplateType: "Дизайн на шаблона",
    designTemplates: {
      classic: "Класически",
      modernDark: "Модерен тъмен",
      gradient: "Градиент",
      businessPro: "Бизнес Про",
    }
  }
};
